### PR TITLE
added 1 wk ahead case forecast for the week of 2021-09-20 from UT-GISAG team.

### PR DESCRIPTION
**Pull request by mrahman-8**

### CODE REVIEW

**Comment by eycramer** [comment]
Hi @mrahman-8,

Thank you for your new submission to the forecast hub! 

We have not merged your pull request because there are a few errors with your submission. In your forecast file, the target_end_date has to be a Saturday, and you have included 2021-09-26 as a target_end_date, which is a Sunday. 

Additionally, in the metadata file, the methods text has to be 200 characters or fewer and you currently have 217.

**Comment by eycramer** [comment]
Hi, 

Your submission is still failing checks because you have predicted higher values than are present in the population for one location. 

Screen Shot 2021-09-28 at 1 57 11 PM

**Comment by mrahman-8** [comment]
Hi,

Thank you for the email. The forecast values are normalized for 100,000 population and hence the error. Does the submission require the base value and not the normalized one?
________________________________
From: Estee Cramer ***@***.***>
Sent: Tuesday, September 28, 2021 2:00 PM
To: reichlab/covid19-forecast-hub ***@***.***>
Cc: Rahman, Ishfaq ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [reichlab/covid19-forecast-hub] added 1 wk ahead case forecast for the week of 2021-09-20 from UT-GISAG team. (#4930)


Hi,

Your submission is still failing checks because you have predicted higher values than are present in the population for one location.

[Screen Shot 2021-09-28 at 1 57 11 PM]<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F60321389%2F135140680-9485c089-d3e7-4e6f-83b3-d9f1679639c8.png&data=04%7C01%7CMdIshfaqUr.Rahman%40rockets.utoledo.edu%7C268b2778d9d64e3572c108d982a9d6f9%7C1d6b1707baa94a3da8f8deabfb3d467b%7C0%7C0%7C637684488234062329%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=166qocyFbhuRRtmOEj1d4AqXfJYALkFbBg%2BZ1jCH%2Bl0%3D&reserved=0>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Freichlab%2Fcovid19-forecast-hub%2Fpull%2F4930%23issuecomment-929495041&data=04%7C01%7CMdIshfaqUr.Rahman%40rockets.utoledo.edu%7C268b2778d9d64e3572c108d982a9d6f9%7C1d6b1707baa94a3da8f8deabfb3d467b%7C0%7C0%7C637684488234072328%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=mb3xYKzXxsrMQGm5LIuhNAebpJGMsWSdGSG1Z3%2Bv0%2Bw%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAR6XHDDQAHMNM273NPNT6ILUEH7DLANCNFSM5EPB6WNA&data=04%7C01%7CMdIshfaqUr.Rahman%40rockets.utoledo.edu%7C268b2778d9d64e3572c108d982a9d6f9%7C1d6b1707baa94a3da8f8deabfb3d467b%7C0%7C0%7C637684488234072328%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ImelfXPJK1PbtA7ZtBNB7BLirGOPLJoja0LPwdKDu18%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CMdIshfaqUr.Rahman%40rockets.utoledo.edu%7C268b2778d9d64e3572c108d982a9d6f9%7C1d6b1707baa94a3da8f8deabfb3d467b%7C0%7C0%7C637684488234082319%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=rG2LQ4zNwIu%2BVwE%2FtIUU6kXaOgTDji1yNYU75s%2FWZRo%3D&reserved=0> or Android<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CMdIshfaqUr.Rahman%40rockets.utoledo.edu%7C268b2778d9d64e3572c108d982a9d6f9%7C1d6b1707baa94a3da8f8deabfb3d467b%7C0%7C0%7C637684488234082319%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=EFYV3mB0OgPXlEbdNa8vKZZLjUMsso5JEXYYhuH0YHk%3D&reserved=0>.

**Comment by eycramer** [comment]
Right, we are collecting base values, not rates or normalized values

**Pull request merged**
