### PR TITLE
Makes the visual change to visualizations by changes absolute numbers to relative rates

### PR DESCRIPTION
**Pull request by ApurvShah007**
Uses the d3.csv() function in the choropleth.js file for changing the absolute numbers to relative rates.

### CODE REVIEW

**Review by Khoale1096 — CHANGES_REQUESTED** [review]
All the files other than the `chloropleth.js` and the `static/locations.csv` should not be merged to master, as they will be created during the weekly deployment.

**Comment by ApurvShah007** [comment]
I agree with that, should have pushed only that file, my bad

**Review by ydhuang28 — CHANGES_REQUESTED** [review]
Agree with @Khoale1096. Also, as per our meeting the correct way to set min and max ranges for the chloropleth map is still under investigation.

**Comment by ApurvShah007** [comment]
Yes there are still changes that need to be pushed

**Comment by ydhuang28** [comment]
Fixing some merge conflicts in the branch (as it's a bit old), will open new PR.

**Pull request closed without merging**
