### PR TITLE
Forecast have been revised.

### PR DESCRIPTION
**Pull request by odalgic**
Covid19sim-Simulator
Forecast have been revised and corrected! The issue with underestimating the deaths have now been fixed.

### CODE REVIEW

**Comment by hannanabdul55** [comment]
@odalgic could you remove the entry `2020-06-21-Covid19Sim-Simulator.csv` from `validated_files.csv` and `locally_validated_files.csv` to trigger a Travis check on the modified file? Thanks.

**Comment by nickreich** [comment]
also, @odalgic can you provide a more detailed rationale for the update. Typically we do not allow for revisions to forecasts once they have been submitted unless the revision is fixing a clear bug in the data processing code as opposed to a model error.

**Comment by odalgic** [comment]
@hannanabdul55 the files that I have do not that entry. Could you please advise?
@nickreich because of a missed step in the process, the projections were calculated using data from the previous week and was not accounting for the new data.

**Comment by hannanabdul55** [comment]
@odalgic can you pull latest changes from master? I think it will re-run the check on the updated files then.

**Pull request closed without merging**
