### PR TITLE
Expert consensus distribution

### PR DESCRIPTION
**Pull request by tomcm39**

### CODE REVIEW

**Comment by nickreich** [comment]
Thanks for the submission @tomcm39 ! We made some late-breaking changes to the data model. Sorry for changing this on you mid-stream, but we wanted to do it sooner rather than later.

We changed the data model to include two optional columns forecast_date and target_end_date. We apologize for the last-minute change. Would you be able to look at [the description here](https://github.com/reichlab/covid19-forecast-hub#data-model) and add those columns if possible in the same column order as the bullets?

**Comment by nickreich** [comment]
Also, could you include a metadata file in the format of other files in the repo and remove the 8-week ahead forecast from the file submitted?

**Comment by tomcm39** [comment]
No problem. I added a meta file, license, included two additional columns as requested, and remove 8 wk ahead forecasts.

**Comment by tomcm39** [comment]
Added back the 8 week forecast. Let me know if all the files look ok!

**Pull request merged**
