### PR TITLE
MIT Update 0706

### PR DESCRIPTION
**Pull request by MichaelLLi**
## Description

Please include a brief description of your change.  

Updated model to capture 2nd wave better, and add case predictions

If you are **adding new forecasts** to an existing model, please include the following details:- 
- Team name:  MIT
- Model name that is being updated:  DELPHI
---

## Checklist

- [x] Specify a proper PR title with your team name.
- [x] All validation checks ran successfully on your branch. Instructions to run the tests locally is present [here](https://github.com/reichlab/covid19-forecast-hub/wiki/Running-Checks-Locally).

### CODE REVIEW

**Comment by nickreich** [comment]
@MichaelLLi this forecast is failing our new validation checks that we specified in the email that went out last week. Please revise and resubmit these forecasts. thanks!

**Comment by MichaelLLi** [comment]
@nickreich Hi Nick - thanks for this. We thought the new cases endpoint include a cumulative case count (which is what the model directly produces) but it seems like there is only an inc case count and that is causing the error. I am wondering if it would be possible to add a cum case count endpoint?

**Comment by nickreich** [comment]
@MichaelLLi we don't have plans at this time to add a cumulative case target.

**Comment by MichaelLLi** [comment]
I see - in that case we have updated our script to derive the incident cases from our cumulative cases. Thanks!

**Pull request merged**
