### PR TITLE
USC-SI_kJalpha Forecast Update

### PR DESCRIPTION
**Pull request by FrostXTJ**
## Description

We update our forecast on 7/5. 

If you are **adding new forecasts** to an existing model, please include the following details:- 
- Team name: USC
- Model name that is being updated:  SI_kJalpha
---

## Checklist

- [x] Specify a proper PR title with your team name.
- [x] All validation checks ran successfully on your branch. Instructions to run the tests locally is present [here](https://github.com/reichlab/covid19-forecast-hub/wiki/Running-Checks-Locally).

### CODE REVIEW

**Comment by FrostXTJ** [comment]
Please also check our issues when trying to submit county-level data [here](https://github.com/reichlab/covid19-forecast-hub/issues/716).

**Comment by nickreich** [comment]
@FrostXTJ can you add the county-level forecasts in this PR? We want this as a live test for the new format.

**Comment by nickreich** [comment]
@FrostXTJ this forecast is failing our new validation checks that we specified in the email that went out last week. Please revise and resubmit these forecasts. thanks!

**Comment by FrostXTJ** [comment]
@nickreich Thank you for updating the scripts! Now our report passes v2-check.

**Pull request merged**
