### PR TITLE
COVID-19Predict: Merging forecast starting at 2021-11-07

### PR DESCRIPTION
**Pull request by AustinMathuw**

### CODE REVIEW

**Comment by eycramer** [comment]
Hi @AustinMathuw, 

This validation is failing because we only accept county-level forecasts for "inc case" targets. 

-Estee

**Comment by AustinMathuw** [comment]
Yes, I see that, fixing the code now.

Thank you!
- Austin

**Comment by AustinMathuw** [comment]
There we go. Thanks for your help @eycramer !

**Comment by Serena-Wang** [comment]
Hi @AustinMathuw,

We are sorry that we had to revert your pull request because we found a typo in your metadata file later in our data processing process. Unfortunately, the typo was in our wiki page and it propagated all the way to PR check. Sorry for all of the confusion. 

Could you create a new pull request and use `institution_affil` in your metadata instead? 

Thank you!

**Pull request merged**
