### PR TITLE
Delete 2021-12-26-BPagano-RtDriven.csv

### PR DESCRIPTION
**Pull request by rjpagano**
Deleting 2021-12-26-BPagano-RtDriven.csv so that I can resubmit with the addition of incident hospitalizations forecast.

### CODE REVIEW

**Comment by rjpagano** [comment]
Resubmitted 2021-12-26-BPagano-RtDriven.csv with unchanged death and case forecast but added hospitalization forecast.

**Comment by rjpagano** [comment]
Uploaded this week's forecast:  "2021-12-27-BPagano-RtDriven.csv", now including hospitalization forecasts.

**Comment by nickreich** [comment]
@rjpagano

**Comment by nickreich** [comment]
@rjpagano We are looking into this - I think this might be a bug in our validations. My understanding is that this file has the original submission (which included only case/death forecasts) but this file also adds some new rows that are hospitalization forecasts, correct?

**Comment by rjpagano** [comment]
Yes, that is correct for "2021-12-27-BPagano-RtDriven.csv" submitted as more comprehensive forecast to replace "2021-12-26-BPagano-RtDriven.csv".

**Comment by nickreich** [comment]
Ok - actually, there might be a simpler fix for this:
1. can you move the 2021-12-27 file to the correct folder (right now it is just in the `data-processed` folder.
2. can you remove the changes to the 2021-12-26 forecast submission from this PR?

I think if you submit a new 2021-12-27 forecast file that has the same case/death values as the one from 12-26 and add the hospitalizations (and don't try to change the 12-26 file) then it should pass ok.

**Comment by rjpagano** [comment]
@nickreich Will do. Apologies for the missteps.

**Comment by nickreich** [comment]
The file is still not in the right location. It is in
`data-processed`
But it should be in 
`data-processed/BPagano-RtDriven/`

**Comment by nickreich** [comment]
I think now if you just remove the 2021-12-26 file from the commit PR (don't delete it, just don't update it) it should go through ok. I think I might be able to do that on this end if that would be easier.

**Comment by rjpagano** [comment]
Yes. Please do. I'm not familiar with that process. Thank you.

**Pull request closed without merging**
