### PR TITLE
Create 2020-07-13-QJHong-Encounter.csv

### PR DESCRIPTION
**Pull request by qjhong**
## Description

If you are **adding new forecasts** to an existing model, please include the following details:- 
- Team name: QJHong
- Model name that is being updated:  Encounter
---

## Checklist

- [ ] Specify a proper PR title with your team name.
- [ ] All validation checks ran successfully on your branch. Instructions to run the tests locally is present [here](https://github.com/reichlab/covid19-forecast-hub/wiki/Running-Checks-Locally).

### CODE REVIEW

**Comment by qjhong** [comment]
@nickreich Hi, Nick, It seems that my data is shifted by 1 week in your latest update at https://viz.covid19forecasthub.org. In this file, I didn't include 1 week ahead forecast, because the week (ending Jul 18) has already started. Please see the previous file "2020-07-11-QJHong-Encounter.csv" for 1 week ahead forecast. Thank you, and sorry for the inconvenience.

**Comment by nickreich** [comment]
@hannanabdul55 can you remove this forecast from the visualization? If I remember correctly, it is difficult to include a forecast in the visualization that does not have a 1-week ahead forecast?

**Comment by hannanabdul55** [comment]
Done. Visualization deployed. @qjhong can you cross verify and let me know if it is fine.

**Comment by qjhong** [comment]
Looks good! Thanks! @nickreich @hannanabdul55

**Comment by qjhong** [comment]
@hannanabdul55 It seems that the graph is shifted by one week again after this week's update at https://viz.covid19forecasthub.org. Not this week's new forecast, but last week's. I guess maybe this file (missing 1 week ahead forecast) causes the trouble. Do you want me to remove it, so maybe your code will use the previous one which includes 1 week ahead forecast?

**Comment by hannanabdul55** [comment]
Oops. Sure, could you raise a PR for that? That would be great! 
Thank you. I can fix the visualization one that PR is in master.

**Pull request merged**
