### PR TITLE
HkPrMobiDyR

### PR DESCRIPTION
**Pull request by chiangwe**
## Description

Please include a brief description of your change.  

---
> _If this section does not apply to you, please delete it in your PR_  

If this is a **new team submission**, please include the following details :-  
- Team name: 
- Model Name: 
- Institution:  
---

> _If this section does not apply to you, please delete it in your PR_  

If you are **adding new forecasts** to an existing model, please include the following details:- 
- Team name: 
- Model name that is being updated:  
---

## Checklist

- [x] Specify a proper PR title with your team name.
- [x] All validation checks ran successfully on your branch. Instructions to run the tests locally is present [here](https://github.com/reichlab/covid19-forecast-hub/wiki/Running-Checks-Locally).

### CODE REVIEW

**Comment by eycramer** [comment]
Hi @chiangwe, 

Thank you very much for submitting your forecasts! 

Because you are trying to submit many historical forecasts, can you please submit 2 different pull requests? 

The first pull request should contain your metadata file (metadata-IUPUI-HkPrMobiDyR.txt) and your latest forecast file (2021-02-22-IUPUI-HkPrMobiDyR.csv). 

The next PR should contain all of your historical forecasts and any documentation you have about the timing of these previous versions. 

You also have an extra file in this PR (IUPUI-HkPrMobiDyR/temp). Can you please remove this when resubmitting? 

Thanks,
Estee

**Comment by chiangwe** [comment]
This is the first pull request that should contain my metadata file (metadata-IUPUI-HkPrMobiDyR.txt) and your latest forecast file (2021-02-22-IUPUI-HkPrMobiDyR.csv). Thank you so much!

**Comment by chiangwe** [comment]
This PR contains all of my historical forecasts.

**Comment by chiangwe** [comment]
> Hi @chiangwe,
> 
> Thank you very much for submitting your forecasts!
> 
> Because you are trying to submit many historical forecasts, can you please submit 2 different pull requests?
> 
> The first pull request should contain your metadata file (metadata-IUPUI-HkPrMobiDyR.txt) and your latest forecast file (2021-02-22-IUPUI-HkPrMobiDyR.csv).
> 
> The next PR should contain all of your historical forecasts and any documentation you have about the timing of these previous versions.
> 
> You also have an extra file in this PR (IUPUI-HkPrMobiDyR/temp). Can you please remove this when resubmitting?
> 
> Thanks,
> Estee

Hi Estee
I hope you are doing well. I have made two PRs as instructed. The first PR (2783648) contains your metadata file (metadata-IUPUI-HkPrMobiDyR.txt) and your latest forecast file (2021-02-22-IUPUI-HkPrMobiDyR.csv). The second PR (fa087a5) contains all of my historical forecasts.

Thank you so much!
Best,
Wen-Hao Chiang

**Comment by chiangwe** [comment]
Hi, EsteeThank you so much for your notes. I have made two separated PRs as instructed. Please let me know if there is any thing I can help to contribute. Best,Wen-Hao Chiang  From: Estee CramerSent: Tuesday, February 23, 2021 11:16 AMTo: reichlab/covid19-forecast-hubCc: chiangwe; MentionSubject: [External] Re: [reichlab/covid19-forecast-hub] Hk pr mobi dy r (#3010) This message was sent from a non-IU address. Please exercise caution when clicking links or opening attachments from external sources.Hi @chiangwe,Thank you very much for submitting your forecasts!Because you are trying to submit many historical forecasts, can you please submit 2 different pull requests?The first pull request should contain your metadata file (metadata-IUPUI-HkPrMobiDyR.txt) and your latest forecast file (2021-02-22-IUPUI-HkPrMobiDyR.csv).The next PR should contain all of your historical forecasts and any documentation you have about the timing of these previous versions.You also have an extra file in this PR (IUPUI-HkPrMobiDyR/temp). Can you please remove this when resubmitting?Thanks,Estee—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Review by ydhuang28 — APPROVED** [review]
These 7 commits should be okay to merge in this PR (metadata change + most recent forecast).

**Comment by ydhuang28** [comment]
@chiangwe could you revert the last commit from this branch, so that we can merge the most current commit and the metadata file first?

**Review by ydhuang28 — CHANGES_REQUESTED** [review]
this commit should be reverted and a PR should be made later when the first 7 commits are merged.

**Comment by chiangwe** [comment]
> this commit should be reverted and a PR should be made later when the first 7 commits are merged.

Hi @ydhuang28 
I have reverted my last commit. Could you help me to merge the first 7 commits? After those are merged, could I also submit the previous forecasting?
Thank you so much!

**Comment by chiangwe** [comment]
> > this commit should be reverted and a PR should be made later when the first 7 commits are merged.
> 
> Hi @ydhuang28
> I have reverted my last commit. Could you help me to merge the first 7 commits? After those are merged, could I also submit the previous forecasting?
> Thank you so much!

@eycramer 
Hi, @eycramer 
I saw that you have merged my PR. I am wondering whether I can commit my previous predictions as well just for references?

Best,
Wen-Hao Chiang

**Comment by eycramer** [comment]
Hi @chiangwe, 

Yes - you can commit your previous predictions with any documentation you have about when those forecasts were made. 

Thanks for bearing with us in figuring this out!

**Comment by chiangwe** [comment]
> Hi @chiangwe,
> 
> Yes - you can commit your previous predictions with any documentation you have about when those forecasts were made.
> 
> Thanks for bearing with us in figuring this out!

Hi @eycramer 
Thank you so much for your quick reply. I am wondering what the format (and the file name) of the documentation is and in which directory I should place it. Also, is this documentation going to be included in the directory "covid19-forecast-hub/data-processed/IUPUI-HkPrMobiDyR/"?

Best,
Wen-Hao Chiang

**Pull request merged**
