### PR TITLE
Fixing directory issue with Notre Dame team submission

### PR DESCRIPTION
**Pull request by confunguido**
Submission from Notre Dame team. Changed the directory name from NotreDame to NotreDame-FRED

### CODE REVIEW

**Comment by nickreich** [comment]
@confunguido I think the error may be that the column name needs to be `value` not `values`.

```
* ERROR IN ' ./data-processed/NotreDame-FRED/2020-04-27-NotreDame-FRED.csv '
("invalid header. did not contain the required columns. header=['forecast_date', 'target', 'location', 'location_name', 'target_end_date', 'type', 'quantile', 'values'], REQUIRED_COLUMNS=['location', 'target', 'type', 'quantile', 'value']",)
```

**Comment by confunguido** [comment]
I think I did something wrong again. I changed the name of the directories. Is there anything else I need to fix?

**Comment by nickreich** [comment]
@confunguido here are instructions for checking your own PR errors:
https://github.com/reichlab/covid19-forecast-hub/wiki/Troubleshooting-Pull-Requests

**Comment by confunguido** [comment]
Thanks @nickreich

**Pull request merged**
