### PR TITLE
Add JHU processed data

### PR DESCRIPTION
**Pull request by jarad**
See data-raw/JHU_IDD/NOTES.md for assumptions made in processing.

### CODE REVIEW

**Comment by jarad** [comment]
Optimistically, I think the errors are due to https://github.com/reichlab/covid19-forecast-hub/blob/master/data-processed/UMass-MechBayes/2020-04-26-UMass-MechBayes.csv

**Comment by nickreich** [comment]
Unfortunately, @jarad unfounded optimism
```
* ERROR IN ' ./data-processed/JHU_IDD-CovidSP/2020-04-27-JHU_IDD-CovidSP.csv '
invalid target name(s): {'16 day ahead cum hosp', '2 day ahead cum cases', '16 day ahead cum cases', '4 day ahead cum cases', '6 day ahead cum cases', '12 day ahead cum cases', '15 day ahead cum cases', '12 day ahead cum hosp', '6 day ahead inc cases', '15 day ahead inc cases', '6 day ahead cum hosp', '2 day ahead inc cases', '5 day ahead cum cases', '20 day ahead cum hosp', '8 day ahead cum cases', '11 day ahead cum cases', '9 day ahead cum hosp', '3 day ahead cum cases', '2 day ahead cum hosp', '1 day ahead cum cases', '18 day ahead cum cases', '12 day ahead inc cases', '20 day ahead cum cases', '13 day ahead cum hosp', '22 day ahead inc cases', '7 day ahead cum cases', '9 day ahead cum cases', '7 day ahead inc cases', '20 day ahead inc cases', '17 day ahead cum hosp', '11 day ahead cum hosp', '19 day ahead inc cases', '3 day ahead inc cases', '5 day ahead cum hosp', '1 day ahead inc cases', '14 day ahead cum cases', '22 day ahead cum cases', '11 day ahead inc cases', '17 day ahead cum cases', '22 day ahead cum hosp', '13 day ahead cum cases', '14 day ahead inc cases', '16 day ahead inc cases', '10 day ahead inc cases', '10 day ahead cum cases', '1 day ahead cum hosp', '21 day ahead inc cases', '4 day ahead cum hosp', '19 day ahead cum cases', '15 day ahead cum hosp', '18 day ahead cum hosp', '18 day ahead inc cases', '21 day ahead cum hosp', '4 day ahead inc cases', '8 day ahead cum hosp', '13 day ahead inc cases', '19 day ahead cum hosp', '10 day ahead cum hosp', '14 day ahead cum hosp', '17 day ahead inc cases', '21 day ahead cum cases', '3 day ahead cum hosp', '5 day ahead inc cases', '8 day ahead inc cases', '9 day ahead inc cases', '7 day ahead cum hosp'}
```

**Comment by nickreich** [comment]
You can follow directions here to see results of PRs:
https://github.com/reichlab/covid19-forecast-hub/wiki/Troubleshooting-Pull-Requests

**Comment by jarad** [comment]
Got it. No cumulative hospitalizations and no inc/cum cases.

**Pull request closed without merging**
