### PR TITLE
JHUAPL-SLPHospEns 12-06-2020

### PR DESCRIPTION
**Pull request by lmullany**
## Description

Initial submission of JHUAPL Pre-smoothed Simulated Linear Pooling Hospitalization Ensemble
---
- Team name: JHUAPL
- Model Name: SLPHospEns
- Institution:  Johns Hopkins University Applied Physics Lab
---
## Checklist

- [X] Specify a proper PR title with your team name.
- [X] All validation checks ran successfully on your branch. Instructions to run the tests locally is present [here](https://github.com/reichlab/covid19-forecast-hub/wiki/Running-Checks-Locally).

### CODE REVIEW

**Comment by eycramer** [comment]
@lmullany can you please update your website url? The url doesn't seem to be working. 

Thanks!

**Comment by lmullany** [comment]
Hi there @eycramer , there is no public accessible website, but my metadata file failed validation when I indicated "None" in the website url field of the metadata file. As a result, I put an internal JHUAPL gitlab site.

**Comment by eycramer** [comment]
Ok - perhaps because the repo isn't public I wasn't able to access it.  I'll approve the pull request.

**Comment by lmullany** [comment]
@eycramer I'm working to find a way to have these moved from an internal JHUAPL gitlab to something publicly facing, and will let you know/update the metadata file if/when that happens.

**Pull request merged**
