### PR TITLE
GT-DeepCOVID ew23

### PR DESCRIPTION
**Pull request by epideep**

### CODE REVIEW

**Comment by jarad** [comment]
Well you "fixed" the tab problem, but now the metadata looks terrible. I suggest that you remove the changes to the metadata to get the forecast accepted and then you can do a separate pull request for the metadata changes.

**Comment by epideep** [comment]
@jarad sorry for that. Trying again. If this doesn't work, I'll remove changes as you suggested.

**Comment by epideep** [comment]
@jarad please let us know if we still need to remove the changes to the metadata. Thanks!

**Comment by jarad** [comment]
if you take a look at the metadata file in this PR, it is one line, i.e. no line returns.

**Comment by epideep** [comment]
Thanks, I just noticed that @jarad. I have removed the changes. I'll fix the metadata and submit another PR.

**Comment by epideep** [comment]
@jarad @nickreich please we are waiting for you to approve the PR

**Pull request merged**
