### PR TITLE
PSI-DRAFT weekly submission (corrected) - 21 Nov 2022

### PR DESCRIPTION
**Pull request by jturtle**
This commit corrects a few forecast issues in our submission file.

### CODE REVIEW

**Comment by micokoch** [comment]
Hi, I see you have another submission that was already merged. Should I close this one or are you going to fix it?

**Comment by jturtle** [comment]
Hi, still trying to fix it.  Thanks

**Comment by jturtle** [comment]
I will make one more attempt at a valid 'retracted' submission file, but am now running out of time.  Does this really need to be a retraction?  I was trying to correct a submission that was 5-10 minutes old....

**Comment by jturtle** [comment]
Hello.  I don't see a way to use the standard CSV-writer in R to make a
valid retraction-submission.  The entire retraction protocol seems like it
is designed for a different situation, so my preference is to use the first
'corrected' file as our submission.  If that is not possible, I would like
to use the first submission.  Please advise.

Thank you,
Jamie

**Comment by micokoch** [comment]
Hi Jamie,

I tried to follow what you're doing here, correct me if I'm wrong:

1. You submitted [this PR (7833)](https://github.com/reichlab/covid19-forecast-hub/pull/7833), which was already merged.
2. You deleted some rows in your CSV file which constitutes an implicit retraction. You can find details on how to address that [here](https://github.com/reichlab/covid19-forecast-hub/wiki/Forecast-Checks) and [here](https://docs.zoltardata.com/fileformats/#retracted-predictions).
3. You edited your csv file in ways that are not correct.
4. Since this didn't work, you deleted your file.

I propose one of these two solutions:
1. Keep the file that is already merged and I will close this PR.
2. Try to fix this forecast retraction. The main thing is that you have to change all rows you want to delete with `NULL`.

Let me know what you think.
Thanks,
Alvaro.

**Comment by micokoch** [comment]
Hi Jamie,
Sorry, it just occurred to me that I can revert your previous pull request, and you can edit your file there. I would close this one, and you can try resubmitting your file. Does that work for you? Please advise.
Alvaro.

**Comment by jturtle** [comment]
Hi Alvaro,
Thank you for your response.  The problem is that R does not have a numeric
NULL class.  So there is no simple route to produce a blank element with no
quotes.

Yes, please revert and I will re-submit.

Thank you,
Jamie

**Comment by micokoch** [comment]
Hi James, sorry, I am just seeing this now. As per your comment in the other PR, I will just close this submission. Apologies.

**Pull request closed without merging**
