### PR TITLE
UT Osiris 2023-09-11

### PR DESCRIPTION
**Pull request by SusanPtak**
## Note

Please include your team name in the title of the pull request. Thank you!

### CODE REVIEW

**Comment by micokoch** [comment]
Hi Susan - yes, I noticed it, too. I'm not sure, and will ask my colleagues to see if they have any ideas.

**Comment by SusanPtak** [comment]
Thanks so much!

**Comment by micokoch** [comment]
Hi Susan. The problem is that you were adding the files in the wrong location. They were added to the base directory of the repository rather than in `data-processed/UT-Osiris`. I fixed the issue, and moved the files to the correct location. For next week, just make sure to submit the files in the correct location. Thanks and have a good week.

**Comment by SusanPtak** [comment]
Thanks and sorry about this.  I'll try this next week.

**Comment by micokoch** [comment]
No problem. I'll be more careful as well.

**Comment by SusanPtak** [comment]
Dear Alvaro,

The final stage of merging still seems to not be happening automatically
(or at least taking a lot longer than previously).  No errors
were reported.  I believe I put the files in the right place.  Any ideas?

Thanks!
Susan

**Comment by micokoch** [comment]
Hi Susan,

I'm glad the validations worked this week, and that seems to be in order.

I suspect the reason your pull request is not merging automatically is because your fork has not been updated. To be clear, your fork seems to be 80 commits behind the master branch.

Captura de pantalla 2023-09-18 a la(s) 1 49 40 p m

Here is how you would update the branch:

Captura de pantalla 2023-09-18 a la(s) 1 45 41 p m

Perhaps if you do that before submitting your pull request next week it will solve the problem? Let's give it a try, as I think that has been a problem for other teams in the past.

Have a good week and let me know if you have more questions or concerns.

Kind regards,
Alvaro.

**Comment by micokoch** [comment]
Hi Susan, I just commented directly on GitHub but wanted to mention my
initial comment had the image order reversed. I fixed it, but just wanted
to let you know in case you got it as an email and it was confusing. Have a
good day.

**Comment by SusanPtak** [comment]
Ahh...thank you.  I'll try that.
I took over submitting from someone else and I think this step didn't get
passed on (I don't use github regularly).
I figured out the flipped images -- thanks.
Thanks again for all your help!
Susan

**Comment by micokoch** [comment]
No problem! Hope it all goes well.

**Comment by micokoch** [comment]
Dear Susan, there is at least one team that had a problem with their submission, which eventually resolved on its own (maybe it was a GitHub issue?). Regarding your November 27 submission, there are two separate items:
1. The "processing your files" delay may be a GitHub issue, or perhaps it's related to a separate UT Osiris submission by @michaelsegzy today.
2. The other submission by @michaelsegzy has at least two problems I can see: (a) there are two files which are being submitted [in this PR](https://github.com/reichlab/covid19-forecast-hub/pull/9034/files) - one is in the wrong location. (b) I looked at the actual file, and although the name changed, the predictions still seem to be for last week.
My suggestion is to close that PR. Just clean your branch and try to re-submit.
I hope that works!

**Comment by SusanPtak** [comment]
Dear Alvaro,

Thank you so much!  My suspicion is I was having a GitHub issue, but
perhaps you are right, that someone/some program recognized that both of us
were trying to submit (I did try to do it not at the same time as he, but
perhaps his account wasn't as closed out as it should be).  And indeed my
co-worker was having the problems you saw:  I think when he initially ran
the code he forgot to update the date, which caused the initial failure
(and of course he was still traveling from the holiday break which makes
everything harder), and in all his attempts to fix things, also managed to
upload a file to the wrong location at some point.  Once he was back we
could work together and fix the date and get rid of the extra file, and
have now successfully submitted.

Thank you again for all your help.
Susan

**Comment by micokoch** [comment]
I'm glad the submission worked. It's often difficult to discover the source of these problems. Have a good week!

**Pull request merged**
