### PR TITLE
Update metadata-Karlen-pypm.txt

### PR DESCRIPTION
**Pull request by deankarlen**
## Note

Please include your team name in the title of the pull request. Thank you!

### CODE REVIEW

**Comment by Serena-Wang** [comment]
Hi @deankarlen,

Thanks for the update. The new metadata passed validation. However, there are some conflicts in your branch that prevent us from merging in this pull request. Could you resolve it on your end?

**Comment by deankarlen** [comment]
The conflict is the metadata file that failed validation because of line length, but then was corrected. I have no idea how to resolve this "conflict".

**Comment by Serena-Wang** [comment]
@deankarlen Could you try "fetch upstream" from your fork?

**Comment by deankarlen** [comment]
Please merge this pull request - done to resolve conflicts. Perhaps I can update the metadata file after this PR is merged.

**Pull request merged**
