### PR TITLE
CU June 7

### PR DESCRIPTION
**Pull request by tkcy**

### CODE REVIEW

**Comment by hannanabdul55** [comment]
Looks like you have some validation errors specified in the Travis build log [here](https://travis-ci.com/github/reichlab/covid19-forecast-hub/builds/170400219). 
Could you fix these before this PR is merged? Thank you!

**Comment by tkcy** [comment]
@hannanabdul55 I can't figure out what the problem is - I just added one line to the metadata

**Comment by jarad** [comment]
According to the linked build log there is a tab ("\t") somewhere where it shouldn't be. Perhaps in front of "June 7 - present: 80contact1x5p"? If you can't get it to pass, you may want to just add the forecasts and then update the metadata in a separate pull request.

**Comment by tkcy** [comment]
@jarad  Thanks, that was it!  And now I know to just look at the bottom of the build log for error messages - i started reading from the top and got completely lost.

**Pull request merged**
