### PR TITLE
LANL-GrowthRate: Adding 2020-07-23 Forecasts

### PR DESCRIPTION
**Pull request by LaCastro**
## Description

- Team name: LANL
- Model name that is being updated:  GrowthRate

Adding 2020-07-23 Forecasts

### CODE REVIEW

**Comment by hannanabdul55** [comment]
@LaCastro you are updating a previously submitted forecast (07/20). Is there a reason for this? Looks good otherwise. Thank you!

**Comment by LaCastro** [comment]
No, I didn't intend to update, and must have missed that yesterday. The 07/20 forecasts don't have any updates and looks like in [#844](https://github.com/reichlab/covid19-forecast-hub/pull/844) they were merged.  I'm not sure why they were getting updated.

**Comment by hannanabdul55** [comment]
Could you merge `master` to your fork and see if it resolves the issue?

**Comment by LaCastro** [comment]
Yes I will do that -- I am out of town away from my computer until sunday afternoon but will try when I return. Sorry for the delay.

**Comment by nickreich** [comment]
I think we might be able to delete the 7-20 file from the PR. if we do 
that, should we just merge the 7-23 file?

**Comment by LaCastro** [comment]
Yes that would work. Thank you!

**Pull request merged**
