### PR TITLE
PandemicCentral-COVIDForest: Initial Forecasts (2021-04-11)

### PR DESCRIPTION
**Pull request by caominhduy**
## Description

If this is a **new team submission**, please include the following details :-  
- Team name: Pandemic Central
- Model Name: COVIDForest
- Institution: University of Dallas

## Checklist

- [x] Specify a proper PR title with your team name.
- [x] All validation checks ran successfully on your branch. Instructions to run the tests locally is present [here](https://github.com/reichlab/covid19-forecast-hub/wiki/Running-Checks-Locally).

### CODE REVIEW

**Comment by Serena-Wang** [comment]
Hi @caominhduy,

Thank you for submitting your new model. We noticed that you already have `PandemicCentral-USCounty` as  your `primary` model. Because we allow each team to only have one `primary` model, please update `team_model_designation` in metadata according to this [wiki page](https://github.com/reichlab/covid19-forecast-hub/blob/master/data-processed/METADATA.md#team_model_designation).

**Comment by caominhduy** [comment]
> Hi @caominhduy,
> 
> Thank you for submitting your new model. We noticed that you already have `PandemicCentral-USCounty` as your `primary` model. Because we allow each team to only have one `primary` model, please update `team_model_designation` in metadata according to this [wiki page](https://github.com/reichlab/covid19-forecast-hub/blob/master/data-processed/METADATA.md#team_model_designation).

Thank you very much for the instruction. We will correct it in another pull request.

**Comment by ydhuang28** [comment]
@caominhduy FYI, if this isn't clear, you can freely choose which of your models to be `primary`; the restriction is only on the number of `primary` models (which is one).

**Comment by caominhduy** [comment]
> @caominhduy FYI, if this isn't clear, you can freely choose which of your models to be `primary`; the restriction is only on the number of `primary` models (which is one).

We understood, but thanks for confirmation!

**Pull request closed without merging**
