### PR TITLE
PSI-DICE weekly submission - 04 Sep 2023

### PR DESCRIPTION
**Pull request by jturtle**

### CODE REVIEW

**Comment by jturtle** [comment]
Hi,
The validation process appears to have failed during the data-download step of environment setup.  Do we need to do anything on our end?
Thank you,
Jamie

**Comment by micokoch** [comment]
Hi Jamie, sorry the delay, I was away yesterday for Labor Day and am only looking at this now. I'm not sure what the problem is, but will look into this and get back to you.

**Comment by elray1** [comment]
I'm not sure what the issue was here -- I just closed and reopened the PR (again) without making any other changes, and validations went through OK.

**Comment by jturtle** [comment]
Thank you Alvaro and Evan for your help resolving this.

**Pull request merged**
