### PR TITLE
UT Osiris 2023-09-04

### PR DESCRIPTION
**Pull request by SusanPtak**
## Note

Please include your team name in the title of the pull request. Thank you!

### CODE REVIEW

**Comment by SusanPtak** [comment]
Dear Alvaro Castro Rivadeneira,

Do you know why my submissions now need this extra layer of verification,
rather than automatically being merged?  This can lead to them not being
submitted on time (which maybe is no longer an issue?).

Thanks,
Susan

**Comment by micokoch** [comment]
Dear Susan,

We removed the extra layer of verification, because it seemed unnecessary and didn't work as we intended.

As for this week's submission, I'm not completely sure, but it seems to me that it was not automatically merged because you opened and then closed [this pull request](https://github.com/reichlab/covid19-forecast-hub/pull/8830), and then submitted [a new pull request](https://github.com/reichlab/covid19-forecast-hub/pull/8831) which underwent a different validation, that doesn't automatically merge.

I was looking at your prior submissions and they were automatically merged.

Unfortunately, this last Monday I was away, and didn't see your submission until Tuesday, but this should be an infrequent occurrence. I also hope your future submissions will merge automatically.

I would say, let's wait and see how your submission performs next week. If it merges automatically - great. If it doesn't, I will merge it manually and look into it a bit deeper.

I hope that works for you, and let me know if it doesn't.

Kind regards,
Alvaro.

**Comment by SusanPtak** [comment]
Dear Alvaro,

Thank you.  I am glad to hear that hopefully going forward the submissions
should automatically merge again.  That's right, except for Monday the 4th
and a week ago Monday (28th), I haven't had problems.  I agree that we can
wait and see how it works next week.

I was confused this past week by the results I received after my first
attempt to submit and why it didn't merge the submission, but didn't report
any error.  (A week ago Monday it stated it needed manual checking, but
this week was less clear).  Unfortunately, I did not document this well, so
now I do not remember exactly what happened.  But that is why I pulled the
first request and tried again -- I thought maybe I had inadvertently made
an error during submission.  I didn't realize that closing one pull and
reopening another would cause the submission to be handled differently.

I understand that Monday was a holiday and that caused the delay, which
isn't the case usually.  No problem.

Thanks so much and hopefully next week all will work well,
Susan

**Comment by micokoch** [comment]
Hi Susan, I will be alert to your submission on Monday, and be sure to follow through if there are any problems. Feel free to contact me if you have any more questions. Have a good rest of your week. Kind regards, Alvaro.

**Comment by SusanPtak** [comment]
Thank you very much!

**Pull request merged**
