### PR TITLE
Columbia_UNC-SurvCon Predictions of 2020-07-12

### PR DESCRIPTION
**Pull request by shanghongxie**
Upload Predictions of 2020-07-12 (US cumulative death and inc case)

If you are adding new forecasts to an existing model, please include the following details:-

Team name: Columbia_UNC
Model name that is being updated: SurvCon

### CODE REVIEW

**Comment by shanghongxie** [comment]
If you are adding new forecasts to an existing model, please include the following details:-

Team name: Columbia_UNC
Model name: SurvCon

**Comment by shanghongxie** [comment]
Hi @eycramer,

We submitted our new forecasts 9 hours ago but it is still not merged yet. Are there any problems there? Thanks!

**Comment by shanghongxie** [comment]
Hi @nickreich ,

We submitted our new forecasts 9 hours ago but it has not been merged yet. Please let me know if there are any formatting issues or problems. Thanks!

**Comment by eycramer** [comment]
Hi @shanghongxie, 

I haven't approved your PR yet because it looks like you deleted your files from 6-16 and 6-28 and typically we don't allow teams to delete prior forecasts. Is there a reason that you deleted these items? 

Thanks,
Estee

**Comment by shanghongxie** [comment]
Hi @eycramer,

Our predictions of 6-16 and 6-18 only included **daily** cumulative death. Last week, these predictions were removed by your team due to the new policy but they were still in my personal repository. To avoid confusing, I deleted them. 

> Hi @shanghongxie,
> 
> I haven't approved your PR yet because it looks like you deleted your files from 6-16 and 6-28 and typically we don't allow teams to delete prior forecasts. Is there a reason that you deleted these items?
> 
> Thanks,
> Estee

**Comment by eycramer** [comment]
Thanks for clarifying!

**Pull request merged**
