### PR TITLE
Retraction to include only 1 wk ahead forecasts

### PR DESCRIPTION
**Pull request by csmith701**
## Note

Please include your team name in the title of the pull request. Thank you!

### CODE REVIEW

**Comment by csmith701** [comment]
Hello, I checked and that was due to an error in the original submission that resulted in the US forecasts being dropped. So the revised file contains all rows from the original submission (with NULL for greater than 1 wk forecasts) plus the US targets that were erroneously dropped in the original file.

**Comment by micokoch** [comment]
I'm going to ask people who know more about this, but the experts on this are currently away, so the response may be a bit delayed.

**Comment by micokoch** [comment]
Hello. As far as we can tell, the "implicit retraction" label is only placed if there are rows that were dropped in the second file. From what I can tell, your original submission has 212,569 additions. Your retraction has 211,687 additions and 207,519 deletions. All the deletions would have to match up to the additions line by line, but the extra rows shouldn't affect the designation of "implicit retraction". Could you verify that this is happening?

**Comment by csmith701** [comment]
Hello, the original csv was 212,568 lines (not including the header) all of which were state-level forecasts. 5,304 pf these lines correspond to 1 week ahead forecasts with the remaining 207,264 being for longer time horizons or for hospitalizations which are in days ahead.

**Comment by micokoch** [comment]
Hello, I did some more sleuthing, and I notice that in your original submission your point forecasts are written as "NA", whereas in your retracted submission you inserted "NULL" for the quantile. I suspect that is the root of the problem. You can try submitting your retraction with these changes and I will help get it passed (if it passes validations).

**Comment by csmith701** [comment]
Apologies for that oversight. I will resubmit tomorrow morning. Thanks for all the help.

**Comment by csmith701** [comment]
@micokoch I've consulted my team and I think considering the continued difficulties we've had with the retraction we'll just close the request and stick with our original submission. Thank you for all the help.

**Pull request closed without merging**
