### PR TITLE
Issue 1800: Refactor truth codes to remove duplicate codes

### LINKED ISSUE #1800: Refactor truth codes for visualization and zoltar upload
Refactor code so that common code for both viz truth and zoltar truth is in one place and then zoltar truth is calculated from that common starting point

### PR DESCRIPTION
**Pull request by Khoale1096**
Closes #1800

### CODE REVIEW

**Review by ydhuang28 — APPROVED** [review]
Locally ran the refactored code and looks good!

**Review by hannanabdul55 — APPROVED** [review]
Looks good. Compared the DataFrames from this change and it does not change anything for all the targets as well as zoltar truth 👍

**Comment by ydhuang28** [comment]
OK, merging then!

**Comment by nickreich** [comment]
should we delete the issue-1800 branch?

**Comment by ydhuang28** [comment]
Just did!

**Pull request merged**
