### PR TITLE
Updated Metadata-UT-Osiris

### PR DESCRIPTION
**Pull request by SusanPtak**
## Note

Please include your team name in the title of the pull request. Thank you!

### CODE REVIEW

**Comment by SusanPtak** [comment]
Dear Alvaro,

Do you know why so many of the forecasts are no longer available on the
visualization webpage of the Covid19 Hub?
https://viz.covid19forecasthub.org

Or do you know whom I can ask?

Thanks so much,
Susan

**Comment by micokoch** [comment]
Hi Susan,
Happy new year. The visualizations depend on the submissions. So, the ones that are greyed out at a given moment haven't submitted for that specific outcome/location/date. If you're asking for UT-Osiris, I suppose your submission doesn't include a national forecast, but if you go by specific states you can see UT-Osiris. If you want to know about a specific outcome/location/date I can look into it for you.

**Comment by SusanPtak** [comment]
Thanks.  I didn't actually notice that UT-Osiris was sneaking in on the
states since most others weren't.  Maybe most people aren't submitting
anymore.
Thanks so much.  Mystery solved.

Susan

**Comment by SusanPtak** [comment]
Dear Alvaro,

Does the national forecast include the US Territories, or is it just the 50
states plus DC?

Thanks,
Susan

**Comment by micokoch** [comment]
Hi Susan,

This is what is stated in our [documentation](https://github.com/reichlab/covid19-forecast-hub/blob/master/data-truth/README.md):
"National hospitalization, i.e. US, data are constructed from these data by summing the data across all 50 states, Washington DC (DC), Puerto Rico(PR), and the US Virgin Islands (VI). The HHS data do not include admissions for additional territories."

I'm not sure how military bases, prisons and the like are handled, but I remember with cases, there were some unassigned counties that meant that states for instance were more than the sum of all counties inside them. HHS defines what constitutes the truth, and there may be more details in this [document](https://www.hhs.gov/sites/default/files/covid-19-faqs-hospitals-hospital-laboratory-acute-care-facility-data-reporting.pdf).

I hope that helps!
Alvaro.

**Comment by micokoch** [comment]
No problem, Susan. I'm happy to help.

**Pull request merged**
