### PR TITLE
Update predictions

### PR DESCRIPTION
**Pull request by epideep**

### CODE REVIEW

**Comment by jarad** [comment]
Please explain why these changes were necessary.

**Comment by epideep** [comment]
> Please explain why these changes were necessary.

@jarad We had trained on Covid tracking data, but their data release had a bug. So we fixed it yesterday and trained again. As the results changed, so we thought we should resubmit.

**Comment by ThomasWolf307** [comment]
The prediction has been published. It is unreasonable to resubmit the prediction. You can submit your new prediction next week.

**Comment by nickreich** [comment]
As we state on the README, we will only allow for forecasts to be submitted up to one day after the forecast date to enforce a level of "real-time"-ness to the data.. I don't think this rises to the level of "extenuating circumstances". You are welcome to submit a new set of forecasts with `2020-05-06` as the `forecast_date`.

**Pull request closed without merging**
