### PR TITLE
Submit 2020-06-25 death forecasts for RobertWalraven-ESG

### PR DESCRIPTION
**Pull request by RobertWalraven**
Uploaded metadata.txt and test data to see if I have the data file right.

- Team name: RobertWalraven
- Model Name: ESG
- Institution:  None

### CODE REVIEW

**Comment by hannanabdul55** [comment]
@RobertWalraven the files need to be added as per the instructions specified [here](https://github.com/reichlab/covid19-forecast-hub/blob/master/data-processed/README.md).

**Comment by hannanabdul55** [comment]
@RobertWalraven looks like you have added the files to the incorrect location. Could you add the files in the `data-processed` folder and conforming to the format specified [here](https://github.com/reichlab/covid19-forecast-hub/blob/master/data-processed/README.md)?

**Comment by RobertWalraven** [comment]
I didn't see any sub-folder for me in the data-processed folder and didn't see any way to add one.

**Comment by Serena-Wang** [comment]
@RobertWalraven You did it in the right way when you committed test file in this path data-processed/RWalraven-ESG/Test. The new folder is created in data-processed on your end. But just because we haven't merged your PR yet, the folder is not shown in the remote master. Please put your forecast file and metadata in this new folder and commit it again.

**Comment by RobertWalraven** [comment]
I just created my subfolder RobertWalraven-ESG in the data-processed folder at RobertWalraven/COVID19-forecast-hub and uploaded my metadata.txt and a test csv file.  Is this the correct place to upload my files?   Then would I normally go to Reichlab/COVID19-forecast-hub and issue a pull request?

Sorry about the confusion on my end.   This is my first experience with GitHub and your website, and the instructions were not really clear on how to set things up.

**Comment by Serena-Wang** [comment]
Yes. Every time when you upload your forecasts, please make sure these files are in data-processed/RobertWalraven-ESG. In this way, all of our checks on pull requests will be triggered properly. Once these files passed the checks, we will merge them to the master branch. 

There is a formatting error in your recent commit. You need to rename metadata to metadata-RobertWalraven-ESG.txt because file name needs to be matched with your folder name. You can also follow this [instruction](https://github.com/reichlab/covid19-forecast-hub/wiki/Troubleshooting-Pull-Requests) to get details of the error and troubleshoot your pull request.

**Comment by RobertWalraven** [comment]
I added a revised metadata file and a new data csv file this morning to the folder data-processed/RobertWalraven-ESG at RobertWalraven/COVID19-forecast-hub, but nothing seems to have happened.   Is there something I'm missing?   I was under the impression that putting the files there would generate an automatic pull.

The two checks above appear to refer to my previous uploads.

The error analysis from Travis CI above seems to say that I have a header field with the name ufeffforecast_date, but when I examine the file, the field appears to be forecast_date.   Any idea what the problem is?

**Comment by Serena-Wang** [comment]
\ufeff is a hidden character. It should be right in front of forecast_date in the header. Although it is not visible in a text editor, it will show in csv parsers. Could you remove it?

Also, there are still some formatting errors in the metadata around line 16 or 20. [Here](https://travis-ci.com/github/reichlab/covid19-forecast-hub/builds/173695175) is the full error message.

**Comment by RobertWalraven** [comment]
OK.  It looks like I finally got it right.

**Comment by Serena-Wang** [comment]
Great! I'm merging this.

**Comment by RobertWalraven** [comment]
Thanks for your help!   I think I now understand the process and how to troubleshoot problems.

**Pull request merged**
