### PR TITLE
LosAlamos_NAU-CModel_SDVaxVar: new prediction & metadata file is corrected

### PR DESCRIPTION
**Pull request by ye-chen-netsci**
metadata file is corrected as requested.

new team submission

Team name: LosAlamos_NAU
Model Name: CModel_SDVaxVar
Institution: Los Alamos National Lab and Northern Arizona University

### CODE REVIEW

**Comment by Serena-Wang** [comment]
Hi @ye-chen-netsci,

Thanks for updating your metadata. Could you resolve the conflict in your file and add your forecast file to this pull request?

**Comment by ye-chen-netsci** [comment]
Hi Serena, I corrected the file and submitted a new pull request on Monday.

Ye

**Comment by ye-chen-netsci** [comment]
Pull request was accepted and then reverted last week b/c of the meta file.

**Comment by Serena-Wang** [comment]
Hi @ye-chen-netsci,

Thanks for the update. All files passed the validation. However, we still have merge conflicts on your branch. Could you resolve it on your end? Please let me know how I can help.

**Pull request closed without merging**
