### PR TITLE
2020-05-10 IHME update (and 2020-05-04 formatting update)

### PR DESCRIPTION
**Pull request by varshaskrish**

### CODE REVIEW

**Comment by nickreich** [comment]
I'm seeing these errors:
```
* ERROR IN ' ./data-processed/IHME-CurveFit/2020-05-10-IHME-CurveFit.csv '
invalid FIPS location: 'Alabama'. row=['2020-05-10', 'Monday day ahead inc hosp', '2020-05-11', '523', 'Alabama', 'point', 'NA', '393.0537']
non-integer number of weeks ahead in 'wk ahead' target: 'Monday day ahead inc hosp'. row=['2020-05-10', 'Monday day ahead inc hosp', '2020-05-11', '523', 'Alabama', 'point', 'NA', '393.0537']
```

**Comment by katiehouse3** [comment]
Could you please:
- [ ] Replace the locations with FIPS codes (https://github.com/reichlab/covid19-forecast-hub/blob/master/template/state_fips_codes.csv) and please include leading zeros
- [ ] Double check your target end dates align with the targets 

here is an example of one of the target end date errors:
```
invalid target_end_date: was not 2 day(s) after forecast_date. diff=1, forecast_date=2020-05-10, target_end_date=2020-05-11. row=['2020-05-10', '2 day ahead inc hosp', '2020-05-11', '523', 'Alabama', 'point', 'NA', '393.0537']
```

**Comment by nickreich** [comment]
I'm seeing two errors (there may be others that haven't been picked up).

1. FIPS codes are incorrect
```
invalid FIPS location: 'Alabama'. row=['2020-05-10', '2 day ahead inc hosp', '2020-05-11', '523', 'Alabama', 'point', 'NA', '393.0537']
```
Are you using the standard FIPS codes provided here? https://github.com/reichlab/covid19-forecast-hub/blob/master/template/state_fips_codes.csv

2. your daily targets are not date-aligned. Your forecast has a `forecast_date` of 2020-05-10. therefore the `1 day ahead ..` target should have `target_end_date` of 2020-05-11. It is important to have the targets align for proper evaluation down the road.
```
invalid target_end_date: was not 2 day(s) after forecast_date. diff=1, forecast_date=2020-05-10, target_end_date=2020-05-11. row=['2020-05-10', '2 day ahead inc hosp', '2020-05-11', '523', 'Alabama', 'point', 'NA', '393.0537']
```

**Comment by nickreich** [comment]
Latest issue is that `target_end_date` column for week ahead targets need to always be saturdays. 
```
target_end_date was not a Saturday: 2020-05-17. row=['2020-05-10', '1 wk ahead inc hosp', '2020-05-17', '01', 'point', 'NA', '408.7032']
```

**Comment by nickreich** [comment]
Still not quite right. It's important to have the week-ahead targets align with the correct Saturday. Please see technical README for more info: https://github.com/reichlab/covid19-forecast-hub/blob/master/data-processed/README.md
```
target_end_date was not the expected Saturday. forecast_date=2020-05-10, target_end_date=2020-05-16. exp_target_end_date=2020-05-09, row=['2020-05-10', '0 wk ahead inc hosp', '2020-05-16', '01', 'point', 'NA', '403.4828']
```

This is our last comment for tonight. For troubleshooting on further PRs, please see the wiki https://github.com/reichlab/covid19-forecast-hub/wiki/Troubleshooting-Pull-Requests

**Comment by nickreich** [comment]
I'm going to close this PR for now, since it seems like it is not being worked on any more. feel free to reopen if needed.

**Pull request closed without merging**
