### PR TITLE
Add note on submissions

### PR DESCRIPTION
**Pull request by micokoch**
## Note

Please include your team name in the title of the pull request. Thank you!

### CODE REVIEW

**Review by nickreich — CHANGES_REQUESTED** [review]
Thank you so much for thinking to make these changes! Could I ask that we rephrase the statement "Current plans are...", as this will require us to revisit this in the fall regardless of what is decided. Could we change the text so that we potentially never have to update it again?

**Comment by micokoch** [comment]
Hi @nickreich - I don't think I achieved true timelessness, but I reworded it as such:
"Submissions are scheduled to restart in fall 2024, in a different format. Information provided on forecast submissions are kept for historical record."
Another option is to just delete the sentence about "Submissions..." Let me know what you prefer and I can update the website notes as well.

**Comment by nickreich** [comment]
Let's just delete the note about submissions.

**Comment by micokoch** [comment]
Hi @nickreich - I deleted the sentence and will do so on the website as well. It should be okay to merge.

**Review by nickreich — APPROVED** [review]

**Pull request merged**
