### PR TITLE
2020-11-09-RobertWalraven

### PR DESCRIPTION
**Pull request by RobertWalraven**
Weekly forecast

Robert Walraven
ESG

### CODE REVIEW

**Comment by eycramer** [comment]
Hi @RobertWalraven, 

Can you please change this PR so that you're not deleting your forecast from 10/12? 
Also, it looks like you've also added your forecast twice so can you please delete the version that is not in the correct folder? 

Thank you!

**Comment by RobertWalraven** [comment]
I originally uploaded today's forecast to the wrong directory and then uploaded it again to the right directory.   I didn't delete the forecast in the wrong directory yet.  Should I do that now?

  When I looked at the wrong directory I noticed that I must have done the same thing for 10/12 because there was a duplicate of that week's submission too.   However, it is possible that I may have uploaded the 10/112 forecast to the wrong directory last.  Is there a way to determine which one is is the correct one?

Also I didn't see a way to cancel the delete PR.  Can you tell me how I should do that?

I didn't see a way to cancel the

**Comment by eycramer** [comment]
I've deleted the extra file uploaded in the wrong directory. The file from 10-12-2020 appears to be an old commit. It won't interfere with our system so I'll merge your PR now.

**Comment by RobertWalraven** [comment]
This was not in the correct directory and there is another file of the same name in the correct directory.  However, since this is the one that the ensemble may be using, leave it alone.

**Pull request merged**
