### PR TITLE
add Apurv's work on changing colormap to use rates

### LINKED ISSUE #1922: Change to using rates instead of absolute numbers
Right now the map and the time chart use absolute numbers. Since different jurisdictions have wildly different population numbers, perhaps the better way to visualize numbers would be to use a rate, i.e., case/mortalities per 1K/10K/100K population.

This is open to suggestions!

### PR DESCRIPTION
**Pull request by ydhuang28**
Changed color map to use rates instead of absolute numbers

Closes #1922

### CODE REVIEW

**Comment by nickreich** [comment]
Can someone post some screenshots of what the new and old map looks like? And/or maybe instructions for loading a test version of the viz locally, so I can see what this looks like in action? I'd like to provide a non-technical review of this feature.

**Comment by ydhuang28** [comment]
Sorry! Wrong branch. Let me open a new one with the correct branch.

**Comment by ydhuang28** [comment]
@nickreich will post in slack!

**Comment by hannanabdul55** [comment]
@ydhuang28 wasn't there a PR for this from @ApurvShah007 itself? What happened to that?

**Comment by ydhuang28** [comment]
That one was behind of `master` so much that when I tried to rebase and merge (in order to remove the files in `vis-master/dist`), GitHub wouldn't let me because of file size issues. So I had to only refactor out the relevant changes and make a new branch with the same name to open new PRs.

**Comment by ApurvShah007** [comment]
Have these changes been merged into the master already? Also I can provide some screenshots to @nickreich if that hasnt already been done!

**Pull request closed without merging**
