### PR TITLE
2021-04-04 MechBayes Update

### PR DESCRIPTION
**Pull request by gcgibson**
National forecast bug forecasted all 0's. Updating with correct forecast.

### CODE REVIEW

**Comment by nickreich** [comment]
@gcgibson can you state for the record that this updated forecast only used data available as of the forecast date?

**Comment by gcgibson** [comment]
@nickreich This is only using data available up to the current date.

**Comment by ydhuang28** [comment]
the viz is now building; merging this for an update to the viz.

**Comment by nickreich** [comment]
@gcgibson the current date? or the forecast date?

**Comment by gcgibson** [comment]
@gcgibson Sorry that was unclear, up the forecast date, the date of the filename.

**Pull request merged**
