### PR TITLE
ISUandPKU model

### PR DESCRIPTION
**Pull request by yumouqiu**
Add the ISUandPKU model, prediction from May 24th

### CODE REVIEW

**Comment by jarad** [comment]
You have two periods before txt in the metadata file name. Also, you do not need to close a pull request and open a new one. Just commit changes to your fork and it will update the pull request here.

**Comment by yumouqiu** [comment]
That is a silly typo. I now know the pull request can be automatic after changes. Thanks!

**Comment by jarad** [comment]
Locations need to be the [two digit numeric code](https://github.com/reichlab/covid19-forecast-hub/blob/master/data-processed/README.md#location) (note that means 01-09 rather than 1-9).

**Comment by jarad** [comment]
[Looks like the target_end_date](https://travis-ci.com/github/reichlab/covid19-forecast-hub/builds/168294765) is not specified correctly. With a 2020-05-25 forecast date, the "1 day ahead" forecasts are for 2020-05-26 and so on.

**Comment by yumouqiu** [comment]
This is what confused me. The data are up to 24th, and 25 is the first day of prediction. Should I put 24 or 25 for the "forecast_date" and how should I name the file, 24 or 25? Thanks.

**Comment by jarad** [comment]
Our definition of the `forecast_date` is the date the forecasts are actually available, i.e. after computation. Since data are generally available, at the earliest, a day late, the `forecast_date` is generally a day after the data are available, although for long running code could be two days later. If your computation was done on the 25th, then that would be the `forecast_date`.

**Comment by jarad** [comment]
Then the targets are all relative to that `forecast_date`. So a `forecast_date` of 2020-05-25 would have a "1 day head" `target_end_date` of 2020-05-26.

**Pull request merged**
