### PR TITLE
Pull Request for RobertWalraven-ESG

### PR DESCRIPTION
**Pull request by RobertWalraven**
Metadata for RobertWalraven-ESG  
- Team name: Robert Walraven

- Model Name: ESG
- Institution:  None (Retired Experimental Physicist working on model at home)
[metadata-Robert Walraven.txt](https://github.com/reichlab/covid19-forecast-hub/files/4843110/metadata-Robert.Walraven.txt)

### CODE REVIEW

**Comment by hannanabdul55** [comment]
@RobertWalraven looks like we are not able to review this PR because it has a lot of files changed. Could you instead create a fresh PR which would show just the changes that you are making so that we can review accordingly? Thanks.

**Comment by hannanabdul55** [comment]
Hi @RobertWalraven , could you please fix the changes in your repository so that we can review your PR and merge? Thanks!

**Comment by RobertWalraven** [comment]
It should be set up now.

 

I’m new to Github, so I’m still on the learning curve trying to figure out how to do things.

**Comment by hannanabdul55** [comment]
Okay, this looks like you're trying to merge 2 local branches to your branch. I don't think this has your changes. You are trying to merge `UT-Covid-master` to `master`. The former branch is a very old branch that has outdated commits.

**Comment by hannanabdul55** [comment]
This PR is obsolete. Closing it for the above reason.

**Pull request closed without merging**
