### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by rjpagano**
## Description

Uploaded metadata-BPagano_RtDriven.tx and 2020-10-04-BPagano-RtDriven.csv.  

---
> _If this section does not apply to you, please delete it in your PR_  

If this is a **new team submission**, please include the following details :-  
- Team name: Bpagano
- Model Name: RtDriven
- Institution: NA
---

> _If this section does not apply to you, please delete it in your PR_  

If you are **adding new forecasts** to an existing model, please include the following details:- 
- Team name: 
- Model name that is being updated:  
---

## Checklist

- [ ] Specify a proper PR title with your team name.
- [ ] All validation checks ran successfully on your branch. Instructions to run the tests locally is present [here](https://github.com/reichlab/covid19-forecast-hub/wiki/Running-Checks-Locally).

### CODE REVIEW

**Comment by rjpagano** [comment]
Thank you very much!

**Comment by Serena-Wang** [comment]
Hi @rjpagano,

Thank you for uploading your model. Please relocate your model folder to data-processed/ folder.

**Comment by rjpagano** [comment]
I have little experience with github. Can you please tell me how to relocate my model folder to data-processed/ folder?

I have created folder, 'BPagano-RtDriven' containing '2020-10-04-BPagano-RtDriven.csv' and 'metadata-BPagano_RtDriven.txt' in
'rjpagano/covid19-forecast-hub/data-processed'

Do I issue another pull request to relocate this folder to
'https://github.com/reichlab/covid19-forecast-hub' https://github.com/reichlab/covid19-forecast-hub ?

I would appreciate you guidance.

Thank you,

Bob

**Comment by Serena-Wang** [comment]
Yes, that is the right way to do it. Please rename your metadata to "metadata-BPagano-RtDriven.txt" and also remove your files in /data-locations in a new commit. 

In the future, you can also refer to this [page](https://github.com/reichlab/covid19-forecast-hub/wiki/Troubleshooting-Pull-Requests) to troubleshoot your pull request.

**Comment by rjpagano** [comment]
I'm getting closer to passing your tests!

Can you tell me specifically what I need to change in my .csv file to address the following error?

* ERROR IN ./data-processed/BPagano-RtDriven/2020-10-04-BPagano-RtDriven.csv
invalid location for target. location='1', target='1 wk ahead cum death'. row=['2020-10-04', '1 wk ahead cum death', '2020-10-10', '1', 'point', 'NA', '2580.897']

Thank you.

**Comment by rjpagano** [comment]
Thank you for your help so far.
I'm getting closer to passing your tests!

Can you tell me specifically what I need to change in my .csv file to address the following error?

* ERROR IN ./data-processed/BPagano-RtDriven/2020-10-04-BPagano-RtDriven.csv
invalid location for target. location='1', target='1 wk ahead cum death'. row=['2020-10-04', '1 wk ahead cum death', '2020-10-10', '1', 'point', 'NA', '2580.897']
Thank you.

**Comment by ydhuang28** [comment]
Referring to the previously failed validation, it could be that your locations are labelled "1"; location codes should be two-digit, so Alabama should be "01", Alaska should be "02", etc.

**Comment by rjpagano** [comment]
Success!  Thank you.

**Comment by rjpagano** [comment]
It passed! Thanks to one and all.

**Comment by rjpagano** [comment]
Is my forecast submission complete? What's the process from here?
Again, thank you.

**Pull request merged**
