### PR TITLE
YYG: add historical daily projections

### PR DESCRIPTION
**Pull request by youyanggu**
Because many groups are submitted all of their projections, not just their weekly CDC projections, we feel that it is only fair that we submit all of our projections as well. This allows for fair evaluations.

These projections are all taken from our GitHub with no edits (timestamps should match): https://github.com/youyanggu/covid19_projections/tree/master/reich_forecasts

### CODE REVIEW

**Comment by nickreich** [comment]
Looks like there is some problem with target_end_date alignments. instructions on checking log details here: https://github.com/reichlab/covid19-forecast-hub/wiki/Troubleshooting-Pull-Requests

**Comment by youyanggu** [comment]
We fixed the target labels. The error was due to this specification: "For week-ahead forecasts with forecast_date of Tuesday through Saturday of EW12, a 1 week ahead forecast corresponds to EW13". We previously used EW12 for 1 week ahead.

**Comment by nickreich** [comment]
We will address this mid-week after the dust has settled from submissions this week.

**Comment by youyanggu** [comment]
Sounds good.

**Pull request merged**
