### PR TITLE
2021-01-25-RobertWalreven-ESG

### PR DESCRIPTION
**Pull request by RobertWalraven**
Weekly forecast

- Team name: Robert Walraven
- Model Name: ESG

### CODE REVIEW

**Comment by eycramer** [comment]
Hi @RobertWalraven, can you please upload your forecast again with the corrected file path? Your forecast was not uploaded to your folder and did not go through all the automated checks on our end.

Thank you!

**Comment by RobertWalraven** [comment]
I’ve tried several times to upload the forecast to the right folder but the validation rules won’t let me.   If I simply upload the original file validation says the forecast date is wrong and if I upload the data with today as the forecast date validation says the target_end_date is not correct because it thinks the data is for next week.   Any way around this?

**Comment by eycramer** [comment]
Hi @RobertWalraven, 

Sorry for the confusion with this upload! I think that the reason that the forecast from January 25th is giving error messages is because the forecast dates are formatted incorrectly. Maybe there was an automatic format that occurred in excel? 


Here is the error message I'm seeing on my end: 
image

If the first week ahead end date is January 30th, then the file from 1/26 will continue to have error messages. I believe that that file should be deleted if it has the same values as the file from 2020-01-25. After reformatting the dates in the file from the 25th and deleting the file from the 26th, the upload should work without errors, but if anything else comes up just let me know.

**Comment by RobertWalraven** [comment]
You were right – Excel changed the file.  It took me several tries to get the problems straightened out, but it finally passed validation.

 

I suppose there is no hope of getting my model added to the visualization or to the CDC data for this week?

**Pull request merged**
