### PR TITLE
Survival-Convolution Model for COVID-19 Prediction

### PR DESCRIPTION
**Pull request by shanghongxie**
Dear COVID ensemble modelers,
 
We are a team of biostatisticians working on predicting COVID daily new cases and cumulative deaths using statistical models. We would like to contribute our model to your ensemble modeling efforts. A brief description of our modeling strategy and our in press paper are contained in the metadata file as requested.
 
Please let us know if additional information is needed.

### CODE REVIEW

**Comment by Serena-Wang** [comment]
Hi @shanghongxie,

Thank you for uploading your model. Please follow [metadata wiki](https://github.com/reichlab/covid19-forecast-hub/wiki/Metadata-Checks) to include team_abbr, model_abbr and contact_person (name and email) in your metadata.

**Comment by shanghongxie** [comment]
> Hi @shanghongxie,
> 
> Thank you for uploading your model. Please follow [metadata wiki](https://github.com/reichlab/covid19-forecast-hub/wiki/Metadata-Checks) to include team_abbr, model_abbr and contact_person (name and email) in your metadata.

Hi @Serena-Wang,

I have added team_abbr, model_abbr, and contact_person in our metadata.  Thank you so much!

**Comment by Serena-Wang** [comment]
Hi @shanghongxie,

Thanks for the update. Looks like there are some format errors in the metadata. You can check out the logs in the Travis build linked in this PR under the 'Checks' tab. Here is the [log](https://travis-ci.com/github/reichlab/covid19-forecast-hub/builds/171951896) where you can check the errors.

**Comment by shanghongxie** [comment]
> Hi @shanghongxie,
> 
> Thanks for the update. Looks like there are some format errors in the metadata. You can check out the logs in the Travis build linked in this PR under the 'Checks' tab. Here is the [log](https://travis-ci.com/github/reichlab/covid19-forecast-hub/builds/171951896) where you can check the errors.

Hi @Serena-Wang ,

I have fixed this problem. I have changed our team name and the folder name, file names have been changed as well. I hope it is OK. Please let me know if any other edits needed. Thank you!

**Pull request merged**
