### PR TITLE
updated predictions from auquan for 28 june

### PR DESCRIPTION
**Pull request by vishaltomar28**
## Description

Updated predictions from auquan made as of 28 June

## Checklist

- [X] Specify a proper PR title with your team name.
- [X] All validation checks ran successfully on your branch. Instructions to run the tests locally is present [here](https://github.com/reichlab/covid19-forecast-hub/wiki/Running-Checks-Locally).

### CODE REVIEW

**Comment by hannanabdul55** [comment]
Could you fix the conflicts? Also, can you remove the entry `2020-06-28-Auquan-SEIR.csv` from `code/validation/validated_files.csv` and ` code/validation/locally_validated_files.csv`? Thanks!

**Comment by nickreich** [comment]
@vishaltomar28 please fix as @hannanabdul55 specifies above. Also, just wanting to note that this is fixing a bug in the alignment of US level point estimates and quantiles.

**Comment by vishaltomar28** [comment]
Hey, yes this is for alignment of US point and quantile estimates, rebasing
it with master, will make the changes in 10 minutes.

Vishal

**Comment by vishaltomar28** [comment]
@hannanabdul55 I've made the changes as requested, can you please check if this is okay

**Comment by hannanabdul55** [comment]
Looks good. Merging it.

**Pull request merged**
