### PR TITLE
[CMU-TimeSeries] Add 2023-08-28 predictions

### PR DESCRIPTION
**Pull request by nmdefries**
## Note

Please include your team name in the title of the pull request. Thank you!

### CODE REVIEW

**Comment by nmdefries** [comment]
@micokoch @elray1 It looks like auto-merging is broken or delayed, wanted to be sure y'all saw this.

**Review by micokoch — APPROVED** [review]
It looks good.

**Comment by micokoch** [comment]
> @micokoch @elray1 It looks like auto-merging is broken or delayed, wanted to be sure y'all saw this.

@nmdefries - Thank you for making sure we saw this. There was recently a change in the approval process, which is why it's no longer automatic.

**Comment by nmdefries** [comment]
Thanks! Will approval and merging be done manually in the future?

**Comment by micokoch** [comment]
We have suspended the approval process for now. It should be automated again from now on.

**Pull request merged**
