### PR TITLE
2020-06-18 predictions

### PR DESCRIPTION
**Pull request by josh-wilde**
Initial prediction contributions from the COVID Alliance of MIT faculty and students

### CODE REVIEW

**Comment by Serena-Wang** [comment]
Hi @josh-wilde,

Thank you for uploading your model. Please add a license and contact_person (name and email) in your metadata.

**Comment by nickreich** [comment]
The default license for models coming in to the hub are CC-BY-4.0. We encourage you to use this license unless you have strong feelings otherwise.

**Comment by nickreich** [comment]
Also, @josh-wilde we are in process of revising guidelines for metadata revisions. You will need to update your metadata to conform to [these guidelines](https://github.com/reichlab/covid19-forecast-hub/blob/master/data-processed/METADATA.md) before we accept this PR. Here is an [example of a file](https://github.com/reichlab/covid19-forecast-hub/blob/metadata-refactor/data-processed/COVIDhub-ensemble/metadata-COVIDhub-ensemble.txt) that is passing.

Sorry to spring you on this now, but we have just spent a long time redesigning the metadata so it is more streamlined. There will be a new set of checks that will verify that the metadata are in the correct format.

**Comment by josh-wilde** [comment]
Thanks @nickreich. Just updated the metadata. To clarify, do I need a contact_person field in the metadata if I have provided the email addresses for the model_contributors?

**Comment by nickreich** [comment]
No you do not need a contact_person field. You can only have fields that are listed in that metadata dictionary. @hannanabdul55 can you handle the checking/merging of this PR? Can we re-trigger the checks to make sure the metadata is good?

**Comment by josh-wilde** [comment]
@hannanabdul55 I see we were added to the Google Group- please let me know if there are further changes required for us to merge. Also, is there a separate process that we need to go through to ensure that our forecasts appear on the [CDC website](https://www.cdc.gov/coronavirus/2019-ncov/covid-data/forecasting-us.html#state-forecasts) or does the CDC automatically pull all groups from this repo? Thanks for your help!

**Comment by hannanabdul55** [comment]
Hi @josh-wilde, could you please merge the latest changes in master to your branch? A check will be automatically triggered with the latest changes and we can see if everything looks good then.

**Comment by josh-wilde** [comment]
Hi @hannanabdul55, just merged as requested. Let me know if there are other steps required for merging our forecasts into this repo and allowing these forecasts to appear on the CDC website. Thanks!

**Comment by hannanabdul55** [comment]
@Khoale1096 will this rename fail the zoltar upload? If not, can you just go ahead and merge this PR? Thanks!

**Comment by nickreich** [comment]
@josh-wilde As long as you have a fresh forecast in the repo with a forecast_date of anytime Friday through Monday then your forecast should be added to the CDC site. They will pull data directly from this site, and might follow up with you all for more info about your team, but basically it all should be more or less 'automatic'.

**Comment by josh-wilde** [comment]
Excellent- thanks so much!!

________________________________

**Pull request merged**
