### PR TITLE
remove 2020-07-13-QJHong-Encounter.csv (missing 1wk forecase, causing…

### PR DESCRIPTION
**Pull request by qjhong**
… viz issue)

## Description

If you are **adding new forecasts** to an existing model, please include the following details:- 
- Team name: QJHong
- Model name that is being updated:  Encounter
---

## Checklist

- [ ] Specify a proper PR title with your team name.
- [ ] All validation checks ran successfully on your branch. Instructions to run the tests locally is present [here](https://github.com/reichlab/covid19-forecast-hub/wiki/Running-Checks-Locally).

### CODE REVIEW

**Comment by qjhong** [comment]
@hannanabdul55 Done!

**Comment by hannanabdul55** [comment]
Thanks! Merging this.

**Comment by hannanabdul55** [comment]
@qjhong can you check the visualization now? Thanks.

**Comment by qjhong** [comment]
@hannanabdul55 Looks good. Thanks!

**Pull request merged**
