### PR TITLE
Quantori 08May and metadata 

### PR DESCRIPTION
**Pull request by ssemyonov-quantori**

### CODE REVIEW

**Comment by nickreich** [comment]
@ssemyonov-quantori I am going to accept this PR. I strongly encourage you to add a license to your data, so it's clear what the terms are under which you are releasing the data.

**Comment by ssemyonov-quantori** [comment]
@nickreich 
Thanks.
Conditions of data is fully free to use/open source.

I'm not sure which licence is better, but I will try to check.

**Comment by nickreich** [comment]
I'd suggest either Public (although I think this doesn't require people to attribute the data to you) or perhaps better CC-BY-4.0. Other teams have used this. It basically says it's available to use but requires attribution.

**Comment by ssemyonov-quantori** [comment]
@nickreich 

Hi Nicholas,

I dont see our forecast at https://reichlab.io/covid19-forecast-hub/
for Massachusetts, Incident deaths 

Maybe you can advice, why it happens? Thanks!

**Comment by nickreich** [comment]
nothing has been updated yet. later today.

**Pull request merged**
