### PR TITLE
New Submission Team Name

### PR DESCRIPTION
**Pull request by alexrobwong**
Same csv of results submitted on Monday June 8th. 

New Metadata file

License added

### CODE REVIEW

**Comment by nickreich** [comment]
@Khoale1096 can you help us ensure this gets merged appropriately into Zoltar? Should we accept the passing PR and then manually update the Zoltar project info?

**Comment by nickreich** [comment]
Thanks for the submission, @alexrobwong. Changing file/folder names can have strange downstream consequences for our pipeline that we are still working on figuring out. We will address this, but it may take us until late next week to figure out the best way to do this.

**Comment by alexrobwong** [comment]
Hi Nick,

Thank you for your reply. If it's easier, could we simply delete this folder, and create a new PR with a new folder? 

Going forward, we don't need last week's predictions included.

Kind regards,
Alex

**Comment by Khoale1096** [comment]
@nickreich the Zoltar uploading script will consider this as a "new" and will create a new model on zoltar, then uploads the forecasts normally to this new model. The "old" model with the previous name would still be there on Zoltar, but I can manually it to keep things consistent. So in short, if the PR is passing, once it's merged there should be no problem uploading it to Zoltar automatically.

**Comment by nickreich** [comment]
Ok, merged! we'll see what happens!

**Comment by Khoale1096** [comment]
So the build gave an error which indicate the upload to zoltar failed. It turned out that I need to remove the "old" model on Zoltar first before this "new" model can be added in, since they share the same `model_name` in metadata file, which serves as the ID for the model on Zoltar, and there can't be two models sharing the same ID. I removed the "old" model and the "new" model is now added to Zoltar successfully. Sorry for the confusion if I cause any!

**Comment by alexrobwong** [comment]
Thank you both for taking the time and consideration to ensure that this update was incorporated successfully!

Please let us know if you need anything else from us in order to complete the change; we will plan to submit updated forecasts tomorrow under the new name.

**Pull request merged**
