### PR TITLE
YYG: Add daily forecasts

### PR DESCRIPTION
**Pull request by youyanggu**

### CODE REVIEW

**Comment by nickreich** [comment]
@youyanggu Your files are failing the validations because we are no longer accepting daily targets (except for hospitalizations). Can you please update these files and resubmit?

**Comment by nickreich** [comment]
Actually, the error I'm seeing is also about column names:
```
* ERROR IN  ./data-processed/YYG-ParamSearch/2020-07-04-YYG-ParamSearch.csv
invalid header. did not exactly contain the required columns. diff={'location_name'}, header={'value', 'quantile', 'type', 'location_name', 'location', 'target', 'forecast_date', 'target_end_date'}, required_columns={'target_end_date', 'value', 'quantile', 'type', 'location', 'forecast_date', 'target'}
* ERROR IN  ./data-processed/YYG-ParamSearch/2020-07-05-YYG-ParamSearch.csv
invalid header. did not exactly contain the required columns. diff={'location_name'}, header={'value', 'quantile', 'type', 'location_name', 'location', 'target', 'forecast_date', 'target_end_date'}, required_columns={'target_end_date', 'value', 'quantile', 'type', 'location', 'forecast_date', 'target'}
```

**Comment by youyanggu** [comment]
Oh, your email last week said that the new format will be in place starting on July 6, so we removed the location_name and daily targets for forecasts starting on July 6. Should we remove them for these two forecasts as well?

**Comment by nickreich** [comment]
yes, sorry. we were not clear in that email. but yes, please remove them 
for these two forecasts as well. Thanks!

**Pull request merged**
