### PR TITLE
Update RobertWalraven-ESG for today

### PR DESCRIPTION
**Pull request by RobertWalraven**
Replace earlier file with corrected data

- Team name: RobertWalraven
- Model name that is being updated:  ESG
---

## Checklist

- [ ] Specify a proper PR title with your team name.
- [ ] All validation checks ran successfully on your branch. Instructions to run the tests locally is present [here](https://github.com/reichlab/covid19-forecast-hub/wiki/Running-Checks-Locally).

### CODE REVIEW

**Comment by hannanabdul55** [comment]
@RobertWalraven  apologies if it was mentioned earlier, what is the reason for these deletions?

**Comment by RobertWalraven** [comment]
I was trying to delete files that had invalid data that I uploaded when I was first trying to get everything going..  For example, I didn't realize initially that you wanted incident numbers to be the sum of the week rather than just the last day of the week, so the numbers were low by a factor of 7.

However, I don't mind if you just leave them on the system.   I can annotate what is wrong with each one.

BTW, I was looking at some of the other model predictions and noted that the only county data being reported was for inc cases.  I thought you also wanted inc deaths - is that no longer the case?

**Comment by RobertWalraven** [comment]
I've restored the files I deleted.   Can we resolve whatever the problem is so that my data can be considered for this week's ensemble?

**Comment by Serena-Wang** [comment]
Hi @RobertWalraven,

You can still submit county-level incidence death data. I'm merging this PR now.

**Pull request merged**
