### PR TITLE
Add new forecasts (2020-10-11)

### PR DESCRIPTION
**Pull request by sakethsundar**
## Description

Add new forecasts (2020-10-04) 

> _If this section does not apply to you, please delete it in your PR_  

If you are **adding new forecasts** to an existing model, please include the following details:- 
- Team name: MIT-CriticalData
- Model name that is being updated:  MIT_CritData-GBCF
---

## Checklist

- [X ] Specify a proper PR title with your team name.
- [ X] All validation checks ran successfully on your branch. Instructions to run the tests locally is present [here](https://github.com/reichlab/covid19-forecast-hub/wiki/Running-Checks-Locally).

### CODE REVIEW

**Comment by nickreich** [comment]
@sakethsundar Please resolve the conflict and push your changes so the validation scripts can run.

**Comment by nickreich** [comment]
The conflict still exists. can you please just revert your locally_validated_files.csv to match the master branch to avoid the conflict?

**Comment by sakethsundar** [comment]
will fix ocally_validated_files.csv with today's forecasts. Sorry did not notice the comment.

**Comment by sakethsundar** [comment]
@Serena-Wang @nickreich can you please merge this PR before it goes out of sync for locally validated files? Thank you for your help!

**Comment by Serena-Wang** [comment]
Hi @sakethsundar, 

Please remove code/validation/locally_validated_files.csv in your commit. Thanks!

**Comment by sakethsundar** [comment]
> Hi @sakethsundar,
> 
> Please remove code/validation/locally_validated_files.csv in your commit. Thanks!

i am not sure how to remove that. I have overwritten my version with master version few times

**Comment by nickreich** [comment]
I was able to edit the file directly through github to get it synced with our repo. Let's make sure it passes the checks, then it should be good to go.

**Comment by sakethsundar** [comment]
thank you! sorry for the inconvenience. It goes out of sync with every new PR.

**Comment by sakethsundar** [comment]
All checks are passed. Please merge before it goes out of sync. Thank you for your help!

**Pull request merged**
