### PR TITLE
MIT Covid Alliance forecasts for 2020-07-05

### PR DESCRIPTION
**Pull request by josh-wilde**
## Description

MIT Covid Alliance forecasts for 2020-07-05

### CODE REVIEW

**Comment by josh-wilde** [comment]
Hi @nickreich, it seems that the build script is rejecting our county-level case forecasts. It seems that the issue might be with the build script not recognizing county FIPS codes. Would you mind taking a look to confirm this? Please let us know if we need to change our input format, thanks!

**Comment by nickreich** [comment]
@josh-wilde Please do not change your forecasts! we are in process of switching over the validation code and will re-run the new checks on these files. stay tuned!

**Comment by josh-wilde** [comment]
@nickreich that's what we expected- thanks!

**Comment by nickreich** [comment]
@josh-wilde 
Good news: your file has been run using the new check. 
Bad news: there are a few errors.
Good news: they appear to be easy to fix. Nouns in the targets should be singular, e.g. "1 wk ahead inc case", "...cum death", etc....  I see this error:
```
invalid target name(s): {'2 wk ahead inc deaths', '2 wk ahead cum deaths', '3 wk ahead inc cases', '8 wk ahead inc deaths', '5 wk ahead cum deaths', '8 wk ahead inc cases', '3 wk ahead cum deaths', '6 wk ahead inc cases', '4 wk ahead inc cases', '6 wk ahead inc deaths', '1 wk ahead inc cases', '2 wk ahead inc cases', '1 wk ahead inc deaths', '3 wk ahead inc deaths', '4 wk ahead inc deaths', '8 wk ahead cum deaths', '5 wk ahead inc cases', '5 wk ahead inc deaths', '7 wk ahead cum deaths', '1 wk ahead cum deaths', '4 wk ahead cum deaths', '6 wk ahead cum deaths', '7 wk ahead inc cases', '7 wk ahead inc deaths'}
```

**Comment by nickreich** [comment]
When you submit an update, it should be checked with the new validations.

**Comment by josh-wilde** [comment]
Thanks @nickreich, we'll fix and resubmit. Appreciate the help!

**Comment by nickreich** [comment]
@josh-wilde @jwbaek It's passing! We will merge once we have figured out other moving pieces. Thanks!

**Pull request merged**
