### PR TITLE
remove mean

### PR DESCRIPTION
**Pull request by gcgibson**
## Description

We use the mean for internal debugging. Accidentally included it in update.
---
> _If this section does not apply to you, please delete it in your PR_  

If this is a **new team submission**, please include the following details :-  
- Team name: 
- Model Name: 
- Institution:  
---

> _If this section does not apply to you, please delete it in your PR_  

If you are **adding new forecasts** to an existing model, please include the following details:- 
- Team name: 
- Model name that is being updated:  
---

## Checklist

- [ ] Specify a proper PR title with your team name.
- [ ] All validation checks ran successfully on your branch. Instructions to run the tests locally is present [here](https://github.com/reichlab/covid19-forecast-hub/wiki/Running-Checks-Locally).

### CODE REVIEW

**Comment by hannanabdul55** [comment]
Can you also remove `2020-07-12-UMass-MechBayes.csv` from `validated_files.csv` and `locally_validated_files.csv`?

**Comment by gcgibson** [comment]
@hannanabdul55 Hey it looks like my updates to the csv failed?

**Comment by hannanabdul55** [comment]
Looks like there is a quantile with value `0.501`? --> https://github.com/reichlab/covid19-forecast-hub/pull/821/checks?check_run_id=882109827#step:7:13

**Comment by hannanabdul55** [comment]
Did you add another header accidentally? https://github.com/reichlab/covid19-forecast-hub/runs/882284491?check_suite_focus=true#step:7:17

**Comment by gcgibson** [comment]
I did , nice catch!

**Pull request merged**
