### PR TITLE
Quantori 17 May license, repository meta update and forecast

### PR DESCRIPTION
**Pull request by ssemyonov-quantori**

### CODE REVIEW

**Comment by ssemyonov-quantori** [comment]
@nickreich 
Updated forecast for 17 May

**Comment by ssemyonov-quantori** [comment]
It seems something wrong with the build pipeline itself ;

Quantori data passed the checks

Testing ./data-processed/Quantori-Multiagents/2020-05-08-Quantori-Multiagents.csv ...
✔ Forecast file name = Forecast file path ( Quantori-Multiagents = Quantori-Multiagents )
Testing ./data-processed/Quantori-Multiagents/2020-05-17-Quantori-Multiagents.csv ...
✔ Forecast file name = Forecast file path ( Quantori-Multiagents = Quantori-Multiagents )


The wheel Python error?

---------------------------------------
  Failed building wheel for pymmwr
  Running setup.py clean for pymmwr
  Running setup.py bdist_wheel for pyyaml ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-1bdg2fl8/pyyaml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp1hx3pu8epip-wheel- --python-tag cp36:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for pyyaml

**Comment by ssemyonov-quantori** [comment]
I cant understand what is the issue with the data verification here.

**Comment by nickreich** [comment]
The issue here is one of alignment with target_end_date with the week-ahead targets. I see this error:
```
* ERROR IN ' ./data-processed/Quantori-Multiagents/2020-05-17-Quantori-Multiagents.csv '
target_end_date was not the expected Saturday. forecast_date=2020-05-17, target_end_date=2020-05-30. exp_target_end_date=2020-05-23, row=['2020-05-17', '1 wk ahead inc death', '2020-05-30', '25', 'Massachusetts', 'point', 'NA', '456']
```
Please read the guidance on defining week-ahead targets. For forecasts submitted on Sunday and Monday of a week, the "1 week ahead" forecasts should refer to the coming Saturday.

https://github.com/reichlab/covid19-forecast-hub/blob/master/data-processed/README.md#n-wk-ahead-cum-death

**Comment by ssemyonov-quantori** [comment]
@nickreich 
Thanks, will adjust

**Pull request closed without merging**
