### PR TITLE
UTexas forecast for 2020-04-20 

### PR DESCRIPTION
**Pull request by spencerwoody**

### CODE REVIEW

**Comment by spencerwoody** [comment]
> @spencerwoody Can you add to this commit a metadata file, as there are for other models? Especially important to have the `methods:` field be short but descriptive, and include some information about what the model assumes about interventions. If you go to the online visualization, this is the text that appears when you "hover" on a model.

Please see above.

**Comment by katiehouse3** [comment]
@spencerwoody thank you this looks great. A couple quick changes:

- [ ] can you change targets from "1 week ahead.." to "1 wk ahead.."
- [ ]  we changed the data model to include two optional columns `forecast_date` and `target_end_date`. We apologize for the last-minute change. Would you be able to look at [the description here](https://github.com/reichlab/covid19-forecast-hub#data-model) and add those columns if possible in the same column order as the bullets? 

Let me know if you have any questions/clarifications

**Comment by spencerwoody** [comment]
@katiehouse3 The most recent commit should address these points.

**Comment by nickreich** [comment]
Thanks, @spencerwoody !

**Pull request merged**
