### PR TITLE
JHU_IDD CovidSP 9/13 & 9/20 cum death forecast - data processing bug fix + 10/4 forecast update

### PR DESCRIPTION
**Pull request by eclee25**
## Description

We found a bug in our code that was processing the CSSE data for the cumulative death forecasts. This bug affected the 9/13 and 9/20 cumulative death forecasts, and these are now updated for visualization purposes. Discussed already with @nickreich 

If you are **adding new forecasts** to an existing model, please include the following details:- 
- Team name: JHU_IDD
- Model name that is being updated:  CovidSP
---
## Checklist

- [x] Specify a proper PR title with your team name.
- [x] All validation checks ran successfully on your branch. Instructions to run the tests locally is present [here](https://github.com/reichlab/covid19-forecast-hub/wiki/Running-Checks-Locally).

### CODE REVIEW

**Comment by eclee25** [comment]
I renamed the originally committed files `_error` and the corrected ones have the same file names as before.

**Comment by nickreich** [comment]
@eclee25 please delete the _error files from the PR. They will be retained in the git version history. at some point in the not-too-distant future, we plan on creating a more formal structure to save the versions of forecasts, and at such a time we will pull in previous versions of forecasts.

**Comment by jayb** [comment]
I'm not sure if it's related to this issue, but the September 27 JHU `cum death` forecasts are quite high -- in the range of 400k -- and seem like the result of a bug.

**Comment by eclee25** [comment]
Okay let me check the 9/27 forecasts again. I think I know what the issue might be

**Comment by jayb** [comment]
Just the U.S. forecast, yes.

**Comment by eclee25** [comment]
The cumulative death forecasts should be fixed for all 3 forecasts now - 9/13, 9/20, and 9/27

**Comment by eclee25** [comment]
This fork now includes the JHU_IDD CovidSP forecasts for 10/4

**Pull request merged**
