### PR TITLE
ew10 DeepCOVID submission

### PR DESCRIPTION
**Pull request by epideep**
## Description

If you are **adding new forecasts** to an existing model, please include the following details:- 
- Team name: DeepCOVID
- Model name that is being updated:  DeepCOVID
---

## Checklist

- [ ] Specify a proper PR title with your team name.
- [ ] All validation checks ran successfully on your branch. Instructions to run the tests locally is present [here](https://github.com/reichlab/covid19-forecast-hub/wiki/Running-Checks-Locally).

### CODE REVIEW

**Comment by epideep** [comment]
Hi @hannanabdul55, can you please let me know what the issue is? The automatic messages are not being useful to debug this.

**Comment by hannanabdul55** [comment]
Hi @epideep GitHub actions are facing issues right now. Hence, we're waiting until they're back up and running. Once it is working fine, could you close and reopen this PR so that the validations are run? Thank you!

**Comment by epideep** [comment]
Thanks for the update, @hannanabdul55. Happy to help with that, could you please let us know when it's working again?

**Comment by hannanabdul55** [comment]
Sure, I can do that. 

If you want to track the status by yourself, you can subscribe to the incident [here](https://www.githubstatus.com/incidents/s654n76c1bwr).

**Pull request merged**
