### PR TITLE
Add CDDEP model output

### PR DESCRIPTION
**Pull request by yupengyanghuhu**
Add CDDEP model output

### CODE REVIEW

**Comment by nickreich** [comment]
Thanks for the submission! Just confirming that this forecast only has one day's forecast and it is for today, the day the PR was submitted. Was this intentional?

**Comment by yupengyanghuhu** [comment]
> Thanks for the submission! Just confirming that this forecast only has one day's forecast and it is for today, the day the PR was submitted. Was this intentional?

Hi Mr Reich, thanks for reaching out to me. Yes, we finished building our Global Agent Based Model, for this first time submission we just used DC&Maryland 1 days ahead from 06/01 as an example, the more states and target dates results will be available soon.

**Comment by nickreich** [comment]
Thanks for the info. We are not going to merge for now but will later this week. We are bringing on some new folks to help with PR management later this week and are hoping to use this PR as a training set to help show people how to merge PRs from new teams.

**Comment by yupengyanghuhu** [comment]
> Thanks for the info. We are not going to merge for now but will later this week. We are bringing on some new folks to help with PR management later this week and are hoping to use this PR as a training set to help show people how to merge PRs from new teams.

Sure! Thanks very much. I'll let you know once I get any update

**Pull request merged**
