### PR TITLE
07-04-2020 update from RobertWalraven

### PR DESCRIPTION
**Pull request by RobertWalraven**
07-04-2020-RobertWalraven-ESG update to test new procedures plus quantiles

- Team name:  RobertWalraven
- Model name: ESG

### CODE REVIEW

**Comment by RobertWalraven** [comment]
Node.js failed because it could not find my metafile.   Could this be because you deleted my folder from data-processed earlier today?

**Comment by nickreich** [comment]
@hannanabdul55 I think at least part of the problem here is that we nuked the metadata file. can you add back in?

**Comment by hannanabdul55** [comment]
I think this PR will also be fixed after reverting the script changes. Closing and reopening this PR.

**Comment by hannanabdul55** [comment]
I think you have to rename your metadata file by replacing `Robert Walraven-ESG.csv` to `RobertWalraven-ESG.csv`

**Comment by RobertWalraven** [comment]
I deleted both the metafile and the data file and uploaded them again, but I'm still getting the same message from node.js that it can't find the metafile in my folder (which doesn't exist) in the data-processed folder.

**Comment by RobertWalraven** [comment]
I deleted the metafile and data file and uploaded them again, but I'm still getting a message from node.js that it can't find my metafile in the data-processed/RobertWalraven-ESG folder.

**Pull request merged**
