### PR TITLE
ew18 GT-DeepCOVID

### PR DESCRIPTION
**Pull request by epideep**

### CODE REVIEW

**Comment by nickreich** [comment]
@epideep Can you fix these conflicts and resubmit? You should just be changing the files in your model's subdirectory.

**Comment by epideep** [comment]
> @epideep Can you fix these conflicts and resubmit? You should just be changing the files in your model's subdirectory.

Thanks for the heads up. Working on it.

**Comment by epideep** [comment]
We didn't pass the check. Is there are way to get feedback from Travis? I just noticed that the weekly targets for hospitalizations are not in your list of accepted targets (https://github.com/reichlab/covid19-forecast-hub/blob/master/data-processed/README.md#Data-formatting). I wonder if this may be the problem. Thanks.

**Comment by epideep** [comment]
> We didn't pass the check. Is there are way to get feedback from Travis? I just noticed that the weekly targets for hospitalizations are not in your list of accepted targets (https://github.com/reichlab/covid19-forecast-hub/blob/master/data-processed/README.md#Data-formatting). I wonder if this may be the problem. Thanks.

To follow up this, I got this message from Travis:
`invalid target name(s): {'1 wk ahead inc hosp', '2 wk ahead cum hosp', '2 wk ahead inc hosp', '1 wk ahead cum hosp'}`

**Comment by nickreich** [comment]
Yup, as per the readme, we are not at the moment accepting week ahead hospitalization forecasts, only daily. sorry for the change from the previous project.

**Comment by epideep** [comment]
> Yup, as per the readme, we are not at the moment accepting week ahead hospitalization forecasts, only daily. sorry for the change from the previous project.

@nickreich Sorry, we didn't realize about this. Do you mind if we submit this by tomorrow noon?

**Comment by epideep** [comment]
> > Yup, as per the readme, we are not at the moment accepting week ahead hospitalization forecasts, only daily. sorry for the change from the previous project.
> 
> @nickreich Sorry, we didn't realize about this. Do you mind if we submit this by tomorrow noon?

Update: We changed our hosp predictions from weekly to daily, and passed the checks.

**Pull request merged**
