### PR TITLE
CU July 2 ?

### PR DESCRIPTION
**Pull request by tkcy**
## Description

Please use caution!  I tried to merge upstream/master before pull request but now it's showing 285 files changed instead of just my 5.  Not sure if I did something wrong.

This is also a first test of new formatting code for the CU models so I'm testing out to see if it passes the automated checks. 

---
 

> _If this section does not apply to you, please delete it in your PR_  

If you are **adding new forecasts** to an existing model, please include the following details:- 
- Team name:  CU
- Model name that is being updated:  all
---

## Checklist

- [ ] Specify a proper PR title with your team name.
- [ ] All validation checks ran successfully on your branch. Instructions to run the tests locally is present [here](https://github.com/reichlab/covid19-forecast-hub/wiki/Running-Checks-Locally).

### CODE REVIEW

**Comment by tkcy** [comment]
On further inspection, it definitely looks like this uses older versions of some of your files.  But I don't know how to fix it... I tried to undo the merge but it says nothing to undo.  I also tried pulling again but it says up to date.  Sorry if I've messed things up!

**Comment by nickreich** [comment]
Have you synced with the upstream fork? https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork

**Comment by tkcy** [comment]
@nickreich yes that's what i did, and tried it again just now, it says i'm up to date:


```
sph-tky2104-ehs:covid19-forecast-hub tky2104$ git fetch upstream
sph-tky2104-ehs:covid19-forecast-hub tky2104$ git checkout master
Already on 'master'
Your branch is up to date with 'origin/master'.
sph-tky2104-ehs:covid19-forecast-hub tky2104$ git merge upstream/master
Already up to date.
```

**Comment by tkcy** [comment]
@nickreich But the first time I did it it did say something about a conflict, and wasn't confident in how i resolved it.  (And don't remember what it said or what option i selected)

**Comment by hannanabdul55** [comment]
@tkcy maybe you can try reverting this commit #f9cc6e2e68022814497bfc40826794ae1baf6338 in your branch and then try merging back from `upstream/master`? Alternatively, you can try creating a fresh branch from `upstream/master` and then cherry-picking your commit (#31aad63)  into that branch. (SO link [here](https://stackoverflow.com/a/2474430), just in case)

**Comment by tkcy** [comment]
@hannanabdul55 Thanks. I tried the first option yesterday and nothing happens.

The second option cherry-picking sounds scary, cut can I just abandon my old branch and copy the files back into the new branch?  I'll try that.

**Comment by tkcy** [comment]
Looks like the new branch is ok.  So maybe we just close this pull request and I use the new branch from now on?

**Pull request closed without merging**
