### PR TITLE
Oliver Wyman Updated Submission

### PR DESCRIPTION
**Pull request by alexrobwong**
Submission from Ugur Koyluoglu and Oliver Wyman team. Thank you.

### CODE REVIEW

**Comment by alexrobwong** [comment]
Still resolving our FIPS string / integer compatibility issue. Will submit again in the next 10 minutes. Thank you for your patience!

**Comment by alexrobwong** [comment]
Hi Jarad,

We are still troubleshooting our csv uploading error. It appears that in our csv that we are uploading, our FIPS codes are being read in as strings instead of integers. Any guidance you may have would be greatly appreciated. 

Thank you,
Alex

**Comment by hannanabdul55** [comment]
Hi, can you do a `zfill` of the FIPS code to have exactly 2 digits? So if the FIPS is `2`, the data file should have `02`.

**Comment by alexrobwong** [comment]
Hi Abdul,

Thank you for your recommendation. Am implementing the fix now.

**Comment by alexrobwong** [comment]
`zfill` to make location 2 characters (i.e. 0-->02) fixed data errors. Am resolving the meta data file error now!

**Comment by alexrobwong** [comment]
Hi Abdul, 

Thank you for your patience and help. We have corrected all upload errors - is it possible for the results to be included in this week's visualization? My apologies again for the delay.

Kind regards,
Alex

**Comment by hannanabdul55** [comment]
Could you remove the changes from the locally validated CSV file(as it is generated and should ideally not be changed)?

**Comment by alexrobwong** [comment]
Hi Abdul,

Thank you for your comment, am happy to remove the changes from the locally validated CSV file. Am attempting to roll back my commits regarding changes to this file. 

Please let me know if you envision a better course of action. 

Kind regards,
Alex

**Comment by alexrobwong** [comment]
Hi Abdul,

Would it be better if I deleted the locally validated csv file and then re-locally validated so that its generated properly?

Kind regards,
Alex

**Comment by alexrobwong** [comment]
Hi Abdul,

Kindly wanted to bump my last message in case it was missed! Thank you again for your help.

- Alex

**Pull request closed without merging**
