### PR TITLE
Create 2020-06-24-QJHong-Encounter.csv

### PR DESCRIPTION
**Pull request by qjhong**
## Description

Please include a brief description of your change.  

This is a new team submission. My model is available at qjhong.github.io, with source code at https://github.com/qjhong/covid19

---
> _If this section does not apply to you, please delete it in your PR_  

If this is a **new team submission**, please include the following details :-  
- Team name: Qi-Jun Hong
- Model Name: Covid19 Encounter Model
- Institution:  Brown University
---

---

## Checklist

- [x] Specify a proper PR title with your team name.
- [ ] All validation checks ran successfully on your branch. Instructions to run the tests locally is present [here](https://github.com/reichlab/covid19-forecast-hub/wiki/Running-Checks-Locally).

### CODE REVIEW

**Comment by Serena-Wang** [comment]
Hi @qjhong,

Thank you for uploading your model. Please follow [file structure](https://github.com/reichlab/covid19-forecast-hub/blob/master/data-processed/METADATA.md) and [checklist](https://github.com/reichlab/covid19-forecast-hub/wiki/Metadata-Checks) to add your metadata and license.

**Comment by qjhong** [comment]
@Serena-Wang Thanks for the feedback. I have added my metadata and license.

**Comment by nickreich** [comment]
@qjhong it appears that you have not pushed those new changes to this PR?

**Comment by qjhong** [comment]
Is this because I created another pull request to upload the metadata? @nickreich Sorry this is the first time I collaborate on Github.

**Comment by Serena-Wang** [comment]
It seems that there are some formatting errors in your metadata. You can follow these steps https://github.com/reichlab/covid19-forecast-hub/wiki/Troubleshooting-Pull-Requests to debug. After that, please add your metadata and license in this pull request.

**Comment by qjhong** [comment]
@Serena-Wang @nickreich Thanks for the instruction. The last run was successful. Please let me know if there is further issue.

**Pull request merged**
