### PR TITLE
UVA-Ensemble 2021-11-01

### PR DESCRIPTION
**Pull request by aniruddhadiga**
We have started producing forecasts for incident hospitalizations. Appending the hospitalization forecasts to the county level incident cases submitted on Monday 2021-11-01.
## Note

Please include your team name in the title of the pull request. Thank you!

### CODE REVIEW

**Comment by vidhi-mody** [comment]
The csv file has an extra unnamed column which contains the index/serial numbers (from 0-42424) which is causing the build to fail. The file is expected to have only the following columns: `{ 'target', 'type', 'quantile', 'target_end_date', 'location', 'forecast_date', 'value' }`

**Comment by aniruddhadiga** [comment]
Adding hospitalization forecasts to this weeks file

**Comment by aniruddhadiga** [comment]
Adding hospitalization forecast to this weeks file.

**Comment by Serena-Wang** [comment]
Hi @aniruddhadiga,

Thanks for updating your pull request. It seems like you removed 2021-11-01 forecast file and replaced 2021-10-15 forecast file with today's forecast. If you did not intend to do this, please close this pull request and start a new one to submit this week's forecast. Thank you!

**Pull request closed without merging**
