### PR TITLE
2020-07-26-RobertWalraven-ESG

### PR DESCRIPTION
**Pull request by RobertWalraven**
Test for Monday without county data

- Team name: RobertWalraven
- Model name that is being updated:  ESG

### CODE REVIEW

**Comment by Serena-Wang** [comment]
Hi @RobertWalraven,

It seems that you are removing a bunch of forecast files and also uploading forecasts for 07-20 and 07-26 in this commit. Forecast for 07-20 is already in your folder here. But the files you are removing are not. If you were not intending to do this, could you pull master to your fork and then uploading new forecasts again?

I also notice that you created other pull requests for removing forecasts for 07-06, 07-07 and 07-12. Is there a reason for this?

**Comment by RobertWalraven** [comment]
The files 07-06, 07-07 and 07-12 contain bad data, so I was trying to remove them.   Is there a different way to remove files that have bad data?

 

I’m not sure why the system thought I had uploaded 07-20 because it was already there.

 

07-26 is the new forecast for today.  Should I upload it again and do another pull request?

**Comment by nickreich** [comment]
@RobertWalraven Can you explain what you mean by "bad data"? Typically, we don't allow teams to remove forecasts. Once you make a real-time forecast, you are wedded to it and can't turn back the clock.

**Comment by RobertWalraven** [comment]
Those were some of my first trial uploads where the predictions were completely wrong and didn’t even come close to being correct.   In one case I was reporting the incidents on the last day of the week because I didn’t realize you wanted the total for the week.   After the first three tries I corrected the problems with creating the data so that it could be considered for the ensemble.

 

Is there a way to run a prediction through the ensemble tests beforehand so I don’t have to wait until the ensemble is built to discover that it was rejected because the data did not meet the rules?

**Comment by RobertWalraven** [comment]
Just leave things as they were.  That's ok.

**Comment by RobertWalraven** [comment]
I see that my projections made it through the ensemble tests and were given weights for the ensemble, but is not showing up at viz.covid19forecasthub.org.   I'm a bit puizzled by that.   What am I missing?

**Comment by nickreich** [comment]
This may just be that we haven't updated the "models to include in visualization" list from the previous week. flagging @hannanabdul55 to check. Thanks!

**Pull request closed without merging**
