### PR TITLE
BUG FIX: OliverWyman-Navigator correcting forecasts for Missouri and US national last two weeks.

### PR DESCRIPTION
**Pull request by ddesroches**
The forecast was fit only to data available at the time.

Updating submissions for last two weeks.

### CODE REVIEW

**Comment by ddesroches** [comment]
As noted, we found a bug in our handling of Missouri's forecast (due to the decrease in cumulative confirmed cases on Apr 17) and have corrected that state along with the US national forecast.

**Comment by nickreich** [comment]
Our validation has found an invalidly formatted "retracted" forecast. Are you removing any specific predictions from this file? if so, please follow the retraction format. Thanks!

This is also the first time this validation has been tested, so if it's catching something it shouldn't be, please let us know.

> The forecast 2021-05-02-OliverWyman-Navigator.csv has an invalid retraction. Please review the retraction rules for a forecast in the wiki here - https://github.com/reichlab/covid19-forecast-hub/wiki/Forecast-Checks

**Comment by ddesroches** [comment]
We are not trying to retract any forecast but to replace values for Missouri (location 29) and US due to a bug fix. I tried to follow the guidance from the submission instructions, which says, "If you need to submit an updated forecast for [a bug found], please include a comment in your pull request confirming that there was a bug and that the forecast was fit only to data available at the time.

**Comment by nickreich** [comment]
From the diff, it seems like there are more rows being removed than added: 
image

**Comment by ddesroches** [comment]
You are right -- the replacement May 2 file was not correct. I've corrected that and the change scope looks appropriate.

**Pull request merged**
