### PR TITLE
Revert back to 4-week forecast 

### PR DESCRIPTION
**Pull request by spencerwoody**
@nickreich I believe you mentioned removing SD manually

### CODE REVIEW

**Comment by nickreich** [comment]
@spencerwoody not clear to me how the removal of SD is relevant to this PR. Can you clarify? Also, what is failing here?

**Comment by spencerwoody** [comment]
Any hints on what's breaking here?

**Comment by nickreich** [comment]
Instructions to check PRs are here:
https://github.com/reichlab/covid19-forecast-hub/wiki/Troubleshooting-Pull-Requests

I'm seeing:
```
Testing ./data-processed/UT-Mobility/2020-04-27-UT-Mobility2.csv ...
Error in check_forecast_name_path(i) : 
ERROR: Forecast file name:  UT-Mobility2  does not match Forecast file path:  UT-Mobility
Execution halted
The command "./travis-main.sh" exited with 1.
cache.2
store build cache
```

If this is an update to your current model, we encourage you to keep the same model name but add to your metadata file to describe the updates.

**Comment by spencerwoody** [comment]
sorry, that was some old auxiliary file

**Comment by nickreich** [comment]
Sorry, once more so we have it on record @spencerwoody . what changes are you making in these files here? We are trying to be clear about what is changing when people are making retrospective changes to forecast files.

**Comment by spencerwoody** [comment]
This is simply reverting our forecasts to go out 4 weeks, rather than 6 weeks or 3 weeks

**Comment by nickreich** [comment]
@spencerwoody We would prefer to not modify existing forecasts that have been submitted (for reasons outlined in group email). We are going to close this PR without merging for now and encourage you to submit forecasts in the coming week for however many weeks are appropriate given the state of your model.

**Pull request closed without merging**
