### PR TITLE
New UT forecasts for 2020-04-27; rename

### PR DESCRIPTION
**Pull request by spencerwoody**

### CODE REVIEW

**Comment by spencerwoody** [comment]
Apologies if there are complications that arise for this, but we have decided to rename our team name abbreviation and nickname for our model. That explains the merge conflicts I'm seeing above.

**Comment by nickreich** [comment]
@spencerwoody I think I took care of this, but can you confirm that the files look right to you?

**Comment by spencerwoody** [comment]
@nickreich Looks good to me. Thank you!

**Comment by nickreich** [comment]
Actually - @spencerwoody there is a small issue. In the names of the targets, the targets should have the word "death" in them but not "deaths". The 4-20 file has this correct. the 4-27 file does not. Can you fix and re-submit. I am deleting the 4-27 file from the repo for now, because it is causing build errors.

**Comment by spencerwoody** [comment]
@nickreich Please see #74

**Pull request merged**
