### PR TITLE
Added new MIT-CriticalData forecasts (2021-10-03)

### PR DESCRIPTION
**Pull request by sakethsundar**
## Note

Please include your team name in the title of the pull request. Thank you!

### CODE REVIEW

**Comment by Serena-Wang** [comment]
Hi @sakethsundar,

It seems like you are also submitting the forecast file for week 09/26. If you were not intending to submit it, could you remove it?

**Comment by nickreich** [comment]
Also, the file from last week is in the wrong location.

**Comment by nickreich** [comment]
please reopen a corrected PR if you'd like to resubmit.

**Comment by sakethsundar** [comment]
Sorry I made a mistake last week, adding file to wrong folder. I fixed that this week. So are not we allowed to submit missed forecasts next week?  What should i do for next week?

**Comment by sakethsundar** [comment]
removed the file in the wrong folder and addd only this week forecasts. It got merged this time. Thank you for your help! Sorry for the inconvenience.

**Pull request closed without merging**
