### PR TITLE
JHUAPL-SLPHospEns 2021-06-28 Forecast

### PR DESCRIPTION
**Pull request by lmullany**
## Description

JHUAPL Pre-smoothed Simulated Linear Pooling Hospitalization Ensemble - 06/28/2021 Submission
---
- Team name: JHUAPL
- Model Name: SLPHospEns
- Institution:  Johns Hopkins University Applied Physics Lab
---

### CODE REVIEW

**Comment by lmullany** [comment]
For completeness, submitting last Tuesday's (6/28/2021) SLP Hosp ensemble (As a reminder, this approach only uses data that are submitted by other teams, so result is not effected by timeliness of estimation). 

Will be generating this Tuesday's (7/06/2021) today.

Thanks.

**Comment by nickreich** [comment]
since forecasts from individual teams are sometimes updated post-hoc, it is possible that your ensemble is impacted by the time when it was generated. More generally, we do create [GitHub "tags"](https://github.com/reichlab/covid19-forecast-hub/tags) every week that indicate which version of the repository's history the official COVIDhub-ensemble was built using. For maximal comparability between ensembles, it might be worth using forecasts as of that tag each week.

**Comment by nickreich** [comment]
Do you have a record (e.g. a GitHub commit record from another repository) of that forecast file being generated last week? as a rule, we don't allow late submissions for any model.

**Comment by lmullany** [comment]
no, the ensemble was created today (so no github commit record from another repo). thanks

**Comment by lmullany** [comment]
Nick,

I’ve checked out the 2021-06-28-COVIDhub-ensemble tag, as you suggested, and am re-running the 6/28 SLP Ensemble. Will this be sufficient for me to submit a PR for the 6/28 SLP ensemble?

Thanks much,

Luke




Luke C. Mullany, PhD, MS, MHS
Artificial Intelligence (RQC) / Advanced Analytics
Johns Hopkins University Applied Physics Laboratory
(O): 240-592-3803
(C): 240-280-6184
Professor, Department of International Health
Johns Hopkins Bloomberg School of Public Health
615 N. Wolfe Street, Suite W5009C
Baltimore, MD 21205
***@***.******@***.***> / 410-575-4044
http://tinyurl.com/lmullany





From: Nicholas G Reich ***@***.***>
Sent: Tuesday, July 6, 2021 12:25 PM
To: reichlab/covid19-forecast-hub ***@***.***>
Cc: Mullany, Luke C. ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [reichlab/covid19-forecast-hub] JHUAPL-SLPHospEns 2021-06-28 Forecast (#4263)

APL external email warning: Verify sender ***@***.*** before clicking links or attachments




Do you have a record (e.g. a GitHub commit record from another repository) of that forecast file being generated last week? as a rule, we don't allow late submissions for any model.

**Pull request closed without merging**
