### PR TITLE
ERDC SEIR Model updates for 8-3-2020

### PR DESCRIPTION
**Pull request by erdc-cv19**
Added daily forecasts for the past week
Updated Metadata Website Link to provide more information about the ERDC SEIR Model

### CODE REVIEW

**Comment by hannanabdul55** [comment]
@erdc-cv19 is there a reason why you're removing the file `data-processed/USACE-ERDC_SEIR/2020-07-01-USACE-ERDC_SEIR.csv` ?

**Comment by erdc-cv19** [comment]
I'm still seeing that file in my repo, so I'm not sure what's going on.

**Comment by erdc-cv19** [comment]
We did change that file, to remove 9 wk ahead and 10 wk ahead forecasts since those don't pass anymore.  Other than that I can't figure it out at the moment.  If it gets deleted, we'll find someway to get it back.

**Comment by erdc-cv19** [comment]
Ahh I think I get the confusion now.   I deleted several thousand lines to get rid of 9, 10 and 11 week ahead because I ran a sed command against all of July to make sure they were all cleaned up (we project out to 12 weeks).  It modified a an old projection, not deleting it.  I went ahead and reverted the change, and re-pushed.  

Let me know if you need anything else.

**Pull request merged**
