### PR TITLE
JHU_IDD CovidSP 2021-08-15 submission

### PR DESCRIPTION
**Pull request by csmith701**
## Note

Please include your team name in the title of the pull request. Thank you!

### CODE REVIEW

**Comment by Serena-Wang** [comment]
Hi @csmith701 ,

Thanks for the update. This forecast was submitted two days after the forecast_date on the file. Can you explain why it is coming in late?

**Comment by csmith701** [comment]
Hi @Serena-Wang,

We had bugs in our original model runs we kicked off on Sunday and had to rerun on Monday. I double checked this evening and the data used to calibrate the model included an additional day so I have updated the file name to reflect that fact. Should I also update the forecast date in the csv?

**Comment by Serena-Wang** [comment]
Hi @csmith701,

Yes, please update the forecast date column in the csv and date in file name.

**Comment by csmith701** [comment]
Hi @Serena-Wang - I've updated both the file name and the `forecast_date` column.

**Comment by Serena-Wang** [comment]
Hi @csmith701.

Please also update the `target_end_date` accordingly. I think we could merge this pull request after we took care of the dates. Thank you.

**Comment by csmith701** [comment]
Hi @Serena-Wang, I just want to clarify what you are asking. For this model run, data was used through Sunday 8/15, however the incident targets still correspond to the given target end dates (i.e. the epi weeks ending on Saturday). Are you not able to accept a model where this is the case? To change the `target_end_date` I would need to reprocess the model.

**Comment by Serena-Wang** [comment]
There is a validation error in this pull request. The `forecast_date` column and `target_end_date` column are the same now with a forecasting horizon.

**Comment by csmith701** [comment]
@Serena-Wang I see the issue now. Just uploaded again.

**Comment by Serena-Wang** [comment]
@csmith701 Thank you! Merging this PR now.

**Pull request merged**
