### PR TITLE
Prolix euclidean

### PR DESCRIPTION
**Pull request by loicpottier**
## Note

Please include your team name in the title of the pull request. Thank you!

### CODE REVIEW

**Comment by Serena-Wang** [comment]
Hi @loicpottier,

Thanks for your update. It seems that you submitted two forecast files for 01-11 in this pull request. If they are the same, could you keep the one in your model folder and remove the other one?

**Comment by loicpottier** [comment]
Hi Serena-Wang,
there is only one forecast file for 01-11 in my model folder loicpottier/covid19-forecast-hub. Please excuse me if i have something wrong in this request, i am not very familiar with pull-requests. 

> Hi @loicpottier,
> 
> Thanks for your update. It seems that you submitted two forecast files for 01-11 in this pull request. If they are the same, could you keep the one in your model folder and remove the other one?

**Comment by Serena-Wang** [comment]
@loicpottier No worries. The second file (2022-01-11-prolix-euclidean.csv) is at the root of loicpottier/covid19-forecast-hub. If you remove that file in your fork, the changes will be automatically reflected in this pull request.

**Comment by loicpottier** [comment]
I don't see it at the root of my fork:
[image: image.png]
..?

**Comment by Serena-Wang** [comment]
sorry. It should be on the "prolix-euclidean" branch of your fork.

**Comment by loicpottier** [comment]
Oh! Ok , now, it is removed. Thank you for your work.

> sorry. It should be on the "prolix-euclidean" branch of your fork.

**Pull request merged**
