### PR TITLE
First forecast for ND mobility model

### PR DESCRIPTION
**Pull request by scavany**
This is a new, simpler, model by the Notre Dame team, including the whole US

### CODE REVIEW

**Comment by hannanabdul55** [comment]
Hi,
Thank you for your submission! 
Looks like there are some validation errors in the data. You can check out the logs in the Travis build linked in this PR under the 'Checks` tab. Here is the log where you can check the errors - https://travis-ci.com/github/reichlab/covid19-forecast-hub/builds/171477316#L1335

**Comment by scavany** [comment]
Thanks, am just looking into these errors now!

**Comment by nickreich** [comment]
@scavany Typically we don't accept PRs with forecasts dated from more than 1 day prior. We made an exception here, but why is your file dated from 6/10? The date should refer to the "forecast_date" which we define as the date the forecast was made available. More detail here: https://github.com/reichlab/covid19-forecast-hub/blob/master/data-processed/README.md#forecast_date

**Comment by scavany** [comment]
@nickreich Thanks, and sorry about that! First time I've submitted - will make sure everything is ship-shape for next week

**Pull request merged**
