### PR TITLE
LockNQuay first submission

### PR DESCRIPTION
**Pull request by RussWolfinger**
## Description

Please include a brief description of your change.  

---
> _If this section does not apply to you, please delete it in your PR_  

If this is a **new team submission**, please include the following details :-  
- Team name: LockNQuay
- Model Name: ens1
- Institution:  SAS and Independent
---

> _If this section does not apply to you, please delete it in your PR_  

If you are **adding new forecasts** to an existing model, please include the following details:- 
- Team name: 
- Model name that is being updated:  
---

## Checklist

- [ ] Specify a proper PR title with your team name.
- [ ] All validation checks ran successfully on your branch. Instructions to run the tests locally is present [here](https://github.com/reichlab/covid19-forecast-hub/wiki/Running-Checks-Locally).

### CODE REVIEW

**Comment by RussWolfinger** [comment]
Team name:  LockNQuay
Model name: ens1
Institution: SAS and Independent

**Comment by eycramer** [comment]
Hi, can you please include an email address for at least one of the model contributors in your metadata file? 

The format for model contributors should be:  
name1 (affiliation1) <user@address>, name2 (affiliation2) <user2@address2>

Thanks!

**Comment by RussWolfinger** [comment]
added my email address, thank you

**Comment by eycramer** [comment]
Sorry I didn't see this before - can you please also remove the change from the file, "code/validation/locally_validated_files.csv". I believe  the additional line added to this file is the reason there are conflicts with your branch. 

Thanks!

**Comment by RussWolfinger** [comment]
Apologies, I'm still a newbie with github.  I never originally changed that locally_validatated_files.csv file but just now used the conflict editor to combine things to what appears to be right.   Checks are rerunning and then hopefully we will be good.

**Pull request merged**
