### PR TITLE
Adding 2021-02-15 and 2021-02-08 files

### PR DESCRIPTION
**Pull request by aniruddhadiga**
## Description

Please include a brief description of your change.  

---
> _If this section does not apply to you, please delete it in your PR_  

If this is a **new team submission**, please include the following details :-  
- Team name: 
- Model Name: 
- Institution:  
---

> _If this section does not apply to you, please delete it in your PR_  

If you are **adding new forecasts** to an existing model, please include the following details:- 
- Team name: 
- Model name that is being updated:  
---

## Checklist

- [ ] Specify a proper PR title with your team name.
- [ ] All validation checks ran successfully on your branch. Instructions to run the tests locally is present [here](https://github.com/reichlab/covid19-forecast-hub/wiki/Running-Checks-Locally).

### CODE REVIEW

**Comment by nickreich** [comment]
Please remove the forecast from Feb 8th. In general, we do not allow late submissions.

**Comment by aniruddhadiga** [comment]
Sure, it is done, I was of the opinion that it would be marked as a late
submission. Also, our team name UVA does not appear on the page
https://www.cdc.gov/coronavirus/2019-ncov/cases-updates/forecasts-cases.html
Is it because we did not submit our forecasts last week?

Thanks
Aniruddha Adiga

**Comment by nickreich** [comment]
@aniruddhadiga Yes, I confirmed with CDC that their webpage is updated each week based on the teams that submitted in that week.

**Comment by aniruddhadiga** [comment]
Thanks Nick for confirming.
Aniruddha Adiga

**Comment by aniruddhadiga** [comment]
Hi Estee and Nick,
I am one of the team members of the UVA model. Thanks for the detailed
evaluation you are all providing, it really helps us compare and contrast
our models on a common platform.
I wanted to confirm if the evaluations are based on state level forecasts
alone. The reason I ask this is because we have been providing county-level
forecasts since August 2020 but in the n historical forecasts it does not
reflect. We started providing state-level forecasts recently. Apologies if
this is mentioned in the document and we have missed it.
Thanks
Aniruddha Adiga

**Pull request merged**
