### PR TITLE
Jan26_2021_FirstCommit

### PR DESCRIPTION
**Pull request by ONYLAB**
## Description

Adding the first forecast for team FDANIHASU.
---
> 

If this is a **new team submission**, please include the following details :-  
- Team name: FDANIHASU
- Model Name: Sweight
- Institution: FDA, NIH, and ASU Collaborators
---

## Checklist

- [x] Specify a proper PR title with your team name.
- [x] All validation checks ran successfully on your branch. Instructions to run the tests locally is present [here](https://github.com/reichlab/covid19-forecast-hub/wiki/Running-Checks-Locally).

### CODE REVIEW

**Comment by eycramer** [comment]
Hi @ONYLAB, 

Thanks for your submission! 

Your website link seems to be broken - is there another link you'd like to include? Or a link to your github repository? 

-Estee

**Comment by ONYLAB** [comment]
Hi Dr. Cramer,
Yes, a link to the GitHub repository would be fine for now. Would you like me to do the pull request once more with the edited metadata?
Thank you,
Osman

**Comment by eycramer** [comment]
Yes - that'd be great! when that update is made I'll approve the PR

**Comment by eycramer** [comment]
hi @ONYLAB, 

So sorry for the delay. It looks like some extra files were added to the PR. Can you remove those validated csv files? 

Also, because you're creating an ensemble each week and may be submitting your forecast on Tuesdays instead of Mondays,, could you also just include a statement attesting that  "no observed data after Monday are used for estimating"

**Comment by ONYLAB** [comment]
Thank you very much for all your help!

**Pull request merged**
